### ISSUE TITLE
Incorrect C++ compiler flags

### ISSUE THREAD

**Issue by ascherer** [mgieseki/dvisvgm#101]
When compiling `dvisvgm` in the realm of [TeX Live](https://github.com/TeX-Live/texlive-source) with `g++ 7.3.0`, there are warnings from `cc1plus` about the compiler switch `-Wno-mismatched-tags`:
```
cc1plus: warning: unrecognized command line option '-Wno-mismatched-tags'
```
This compiler flag apparently comes from [`src/Makefile.am`](https://github.com/mgieseki/dvisvgm/blob/master/src/Makefile.am#L265).

**Comment by mgieseki** [comment]
This is currently expected and intended behavior. ;-) 
GCC accepts warning options `-Wno-FOO` even if they are unsupported and only warns about them in case of additional warnings/errors. Nonetheless, this could be improved. It shouldn't be too complicated to add `-Wno-mismatched-tags` only if  the compiler also supports `-Wmismatched-tags`.
