### ISSUE TITLE
feature request: Clipping support for EPS/PDF inclusion

### ISSUE THREAD

**Issue by agrahn** [mgieseki/dvisvgm#104]
Could support for clipping please be added to the `PSfile` and `pdffile` `\special`s, as in this minimal example?

```latex
\documentclass{article}
\pagestyle{empty}

\begin{document}
  \makebox[160bp][l]{\rule{0pt}{80bp}%
    \special{PSfile="example-image.eps" llx=80 lly=80 urx=240 ury=160 rwi=1600 clip}
  }  
\end{document}

```

**Comment by mgieseki** [comment]
Yes, it's also easy to implement. The most complicated part is the recognition of the optional `clip` flag because attributes without values aren't supported in `psfile`/`pdffile` specials yet.
