### ISSUE TITLE
feature request / question: dvisvgm:bbox variant that allows pausing of autom. bbox updating

### ISSUE THREAD

**Issue by agrahn** [mgieseki/dvisvgm#105]
While working on the `dvisvgm.def` driver file  for the graphics package, I sometimes wished there would exist a means to temporarily prevent `dvisvgm` from automatically updating the page bounding box.  Two possible variants of the `bbox` special came to my mind that would allow us to set up such an environment:

```latex
\special{dvisvgm:bbox pause}
%
% stuff typeset here does not contribute to page bbox
% 
\special{dvisvgm:bbox resume}

```
Could something like this be added in a future version? Or is there a way to achieve this with the existing tools?

**Comment by mgieseki** [comment]
It's not possible yet to stop dvisvgm from updating the page bounding box. However, the functionality is already there but it's not available through specials. I'll add it to the next release.
Out of curiosity, what are the scenarios where you want to exclude parts from the box?

**Comment by agrahn** [comment]
Thank you for taking this into consideration!

Original `dvisvgm.def` replaces the Postscript code for transformations (scaling, rotation) by corresponding SVG code. But now, as transformations are applied onto typeset content using raw SVG code, `dvisvgm` cannot take notice of this and calculates the bbox based on the non-transformed content. I would like to be able to set the bbox using `dvisvgm:bbox <wd> <ht> <dp>` based on the final TeX box' dimensions, after the transformations have taken place.

**Comment by mgieseki** [comment]
Ah, OK. Thanks for the info. In this case it might be useful to add an optional flag to the `bbox` specials that allows for applying the current transformation matrix to the box. 
Evaluating raw SVG graphics elements would be much more challenging, though, and isn't on my to-do list at the moment.

**Comment by agrahn** [comment]
> Ah, OK. Thanks for the info. In this case it might be useful to add an optional flag to the `bbox` specials that allows for applying the current transformation matrix to the box/dimensions.

This would be a great addition! As it would allow us to return to transformation via Postscript code.

> Evaluating raw SVG graphics elements would be much more challenging, though, and isn't on my to-do list at the moment.

That's obvious. And I wouldn't dare asking for it ;-).

**Comment by mgieseki** [comment]
I've added the two specials `dvisvgm:bbox lock` and `dvisvgm:bbox unlock`. Also, now the optional modifier `transform` can be appended to the `bbox` specials that specify a bounding box. It transforms the box according to the current transformation matrix.
