### ISSUE TITLE
Some parts that exist in PDF are missing in SVG

### ISSUE THREAD

**Issue by pstricks-fans** [mgieseki/dvisvgm#106]
It is not so convenient to attach the test project here, so let me give you the link to my repository. Here is [https://github.com/pstricks-fans/dvisvgm-errors](https://github.com/pstricks-fans/dvisvgm-errors).

The problem is

The picture of Stephen Hawking that is available in the PDF becomes missing in the SVG. 
The same issue for the radar, the axes that is available in the PDF also becomes missing in the SVG.

Please check it out. Thank  you.

**Comment by agrahn** [comment]
`dvisvgm` doesn't convert bitmaps wrapped into PDF/EPS, such as https://github.com/pstricks-fans/dvisvgm-errors/blob/master/hawking.eps , to SVG. Instead, provide to-be-embedded bitmapped graphics as PNG files. They are not converted to inline SVG and must be shipped alongside the SVG written by `dvisvgm`.

**Comment by pstricks-fans** [comment]
@agrahn How about the radar (missing axes)?

**Comment by mgieseki** [comment]
The conversion of PDF files is still experimental and doesn't yet support all object types allowed there. It might also be possible that Ghostscript doesn't forward all actions being performed to dvisvgm. In this case there wouldn't be much I could do. However, I have to look into the issue first.
Nonetheless, when converting the radar example from DVI or EPS format, all dots and axes are present in the SVG.

**Comment by mgieseki** [comment]
The blue axes and white dots are missing in the radar example due to a bug in dvisvgm's PostScript layer. I'll fix it with the next release.
As Alexander already wrote, dvisvgm doesn't support bitmaps embedded in EPS or PDF files. Thus, `hawking.pdf` can't be converted completely.

**Comment by agrahn** [comment]
It seems that SVG-1.2 does not support inline bitmap. Am I right?

**Comment by mgieseki** [comment]
It should be possible to inline PNG or JPEG data as Base64 stream, e.g.
```svg
<image x="0" y="0" width="300" height="100" xlink:href="data:image/png;base64,<BASE64_DATA>"/>
```
I haven't tested it yet, though.

The much more challenging task would be to extract the bitmap data from the EPS/PDF file because PS operator `image` accepts pretty complex data structures to describe a bitmap.

**Comment by iamtekeste** [comment]
I just run into this issue too, where the images in my pdf are not exported onto the output SVG.
Anything I can do to help to get this to work?

Thank you for making this amazing toolkit!

**Comment by mgieseki** [comment]
If the missing images are bitmaps, I fear you can't do anything automatically with dvisvgm. It doesn't support the corresponding PS/PDF operators yet. Maybe you can postprocess the generated SVG and add the missing bitmaps by inserting proper `<image .../>` elements.

And thanks for the nice feedback!

**Comment by iamtekeste** [comment]
Thank you for the fast reply! 
I am going to give that a shot although I am not sure how I would properly place the image after processing. Like how do I know where the bitmap was located/positioned?

**Comment by mgieseki** [comment]
That's indeed challenging. There is a great PDF utility called `qpdf` that allows to decompress the objects present in a PDF file and provides several options to make them more verbose. Perhaps it's possible to extract the required information from the files created by this tool.

**Comment by iamtekeste** [comment]
Thank you again. I will look into that.

**Comment by iamtekeste** [comment]
Just to be clear though, it is possible to do it with dvisvgm but it is not just implemented yet?

**Comment by mgieseki** [comment]
Yes, that's right. However, the implementation wouldn't be easy either and I currently don't have the time to work on it.

**Comment by iamtekeste** [comment]
Thank you again! No worries, I will try to find something else. Enjoy the weekend.

**Comment by mgieseki** [comment]
Just a small update: I found a quite nice way to process bitmap images embedded in DVI, EPS, and PDF files. The implementation details took some time, though, and I would still consider the current changes, which can be found in the repository, as experimental.
dvisvgm now creates PNGs from the embedded bitmaps and includes the base64 -encoded data into the SVG.

**Comment by iamtekeste** [comment]
This is great news, so if I were to build `dvisvgm` from the source I would see these new changes you made?

And by experimental do you mean it might not work consistently?

**Comment by mgieseki** [comment]
Yes, the latest changes are in the repository. If you build the sources from there, you get the new feature. For example, the above mentioned `hawking.pdf` or `hawking.eps`, which contain a bitmap, will now be converted completely.

> And by experimental do you mean it might not work consistently?

The code is pretty generic and should work with all embedded bitmaps. But I've only tested a couple of files so far, so that there could still be some bugs or things I haven't considered that may lead to conversion issues.

**Comment by iamtekeste** [comment]
Good job! I will test this over the weekend with multiple files and let you know what I find out.
