### ISSUE TITLE
XDG Base Directory Support

### ISSUE THREAD

**Issue by UnicodeAlt255** [mgieseki/dvisvgm#112]
Could support of [XDG Base Directories](https://wiki.archlinux.org/index.php/XDG_Base_Directory) be considered? It would be nice to be freedesktop.org compliant and use XDG base directories by default. Not sure but I believe `$HOME/.dvisvgm` is mainly used as a cache? So then a couple of lines of code should fix it to be `$XDG_CACHE_HOME/dvisvgm`, which would be `~/.cache/dvisvgm` on Linux.

This would reduce home directory pollution and better adhere to how various platforms expect caches/configs to be placed by applications.

**Comment by mgieseki** [comment]
That sounds reasonable. I'll have a look.

**Comment by mgieseki** [comment]
Directory `~/.dvisvgm` is only used to store glyph data generated when bitmap fonts are traced. So it's indeed a good idea to move the files from `~/.dvisvgm/cache` to `$XDG_CACHE_HOME/dvisvgm`.
