### ISSUE TITLE
the words inside svg are very small

### ISSUE THREAD

**Issue by mattmattnice** [mgieseki/dvisvgm#114]
Using the dvisvgm command line (dvisvgm --no-fonts Template.dvi or latex  Template.tex && dvisvgm --no-fonts Template ) to parse the dvi file to get the svg file is very small, the words inside are very small. For example, the following figures, how to make the text inside the svg picture show a big point

latex Template.tex (This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018) (preloaded format=latex))

My latex template(Template.tex) content:
\documentclass[dvisvgm]{standalone}
\usepackage{varwidth}
\usepackage{amsmath,amssymb,amsthm,amsfonts,graphicx}
\usepackage{CJK}
\usepackage[version=4,layout=stacked]{mhchem}
\newcommand{\bbE}{\mathbb{E}}
\newcommand{\bbP}{\mathbb{P}}
\newcommand{\bbI}{\mathbb{I}}
\newcommand{\comp}{\mathsf{c}}
\newcommand{\calK}{\mathcal{K}}
\newcommand{\calM}{\mathcal{M}}
\newcommand{\calG}{\mathcal{G}}
\newcommand{\Var}{\mathrm{Var}}
\newcommand{\leftbrace}{\{}
\newcommand{\rightbrace}{\}}
\newcommand{\harpoon}{\overset{\rightharpoonup}}
\newenvironment{problem}[2][Problem]{\begin{trivlist}
\item[\hskip \labelsep {\bfseries #1}\hskip \labelsep {\bfseries #2.}]}{\end{trivlist}}
\newenvironment{subproof}[1]{\begin{trivlist}
\item[\hskip \labelsep #1 {\em Proof.}]}{\hfill$\Box$\end{trivlist}}

\begin{document}
\begin{CJK*}{UTF8}{gbsn}
\ce{2H2 + O2 ->T[燃烧] 2H2O}
\end{CJK*}
\end{document}

**Comment by mgieseki** [comment]
To enlarge the generated SVG graphic, you can use option `--scale` or `--zoom`, to scale the extends by the specified factor, e.g.
```
dvisvgm --nofonts --zoom=4 Template
```
A negative zoom value omits explicit width and height information in the SVG file so that the graphic extends to the maximum available space:
```
dvisvgm --nofonts --zoom=-1 Template
```

**Comment by mattmattnice** [comment]
Yeah, param --zoom has worked. I found that when svg is very small, the font inside is very light. When svg is enlarged to a certain extent, it is especially clear. Can the font of this svg display at a small size be clearly displayed?Thank  you

**Comment by mgieseki** [comment]
The appearance of the graphics depends on the program used to display the SVG, e.g. the web browser. There isn't much you can do about it. Perhaps it helps a little to replace the paths with actual font data by using option `--font-format` instead of `--no-fonts`, e.g.
```
dvisvgm --font-format=woff --zoom=4 Template
```

**Comment by mattmattnice** [comment]
The generated svg can be displayed normally in the browser, but it will be garbled in our client, some symbols will not display properly; --no-fonts will not have problems

**Comment by mgieseki** [comment]
OK, in this case, it's a limitation of your client's SVG renderer and I guess, there isn't much you can do to improve the display quality.

**Comment by mattmattnice** [comment]
Whether it can be done in latex, control font quality in .tex file

**Comment by mgieseki** [comment]
I don't think so. You could try different fonts that might lead to better rendering results. But that's an issue not related to dvisvgm. Maybe you could ask on [TeX.SX](https://tex.stackexchange.com) to get more helpful information.

**Comment by mattmattnice** [comment]
OK,Thanks

**Comment by mgieseki** [comment]
You're welcome. Hope you'll find a solution.
