### ISSUE TITLE
Manual page is deleted during distclean but not rebuilt

### ISSUE THREAD

**Issue by hpreusse** [mgieseki/dvisvgm#115]
The package delivers a manual page for the dvisvgm binary. This manual page is removed during "make distclean", but not rebuilt during build (just make). My configure options are just "--prefix=/usr".

This makes packaging in Debian a little harder, as our build scripts run a "make distclean" before building the source + binary package. Thanks!

**Comment by mgieseki** [comment]
Building the manual page requires a couple of additional utilities (asciidoc, xmlto, and xsltproc). If they are present, which is checked by `configure`, `dvisvgm.1` should be rebuilt. `configure` should also print a message in case the generation of the manual page has been disabled.

To prevent the removal of `dvisvgm.1` by `make distclean`, you could also patch `doc/Makefile.am` (or `doc/Makefile`) and delete `dvisvgm.1` from rule `distclean-local`.

I hope this info helps a little.

**Comment by hpreusse** [comment]
Thanks for the hint. I now decided to patch Makefile.am. As autoconf does not run fine, I have to patch  Makefile.in too. You may close the ticket.

**Comment by mgieseki** [comment]
Great. Thanks for the feedback. Sorry for the inconveniences but I'm glad you found a solution.
