### ISSUE TITLE
Test suite fails to run on Debian Hurd

### ISSUE THREAD

**Issue by hpreusse** [mgieseki/dvisvgm#116]
We're trying to build the source code on Debian Hurd. Building the binary runs fine, but in the test suite afterwards a test fails. The test suite log is attached.

[test-suite.log](https://github.com/mgieseki/dvisvgm/files/3435826/test-suite.log)

**Comment by mgieseki** [comment]
That's obliviously a rounding issue. Could you check if [this patch](https://github.com/mgieseki/dvisvgm/commit/f156337f7eacb400c9ad824c120bac46222fa361.patch) fixes the test?

**Comment by hpreusse** [comment]
I can confirm that the patch solves the issue on Hurd (I did not test any other arch). Is that a patch I can apply to our source package generally or does Hurd need a specific solution?

**Comment by mgieseki** [comment]
Thanks for the confirmation. It's a general patch I'm going to commit to the dvisvgm sources shortly. Especially, it shouldn't negatively affect other archs but just avoid the unexpected rounding issue you experienced.
