### ISSUE TITLE
PostScript error: undefined in GS_PDF_ProcSet ; TL 2019 ; Debian 10

### ISSUE THREAD

**Issue by FLegendre** [mgieseki/dvisvgm#118]
Sorry to disturb you...

The following MWE yieds this error

$dvisvgm --pdf mwe
PostScript error: undefined in GS_PDF_ProcSet
Operand stack:
    mwe.pdf

$ cat mwe.tex
\documentclass{article}
\begin{document}
Hello, word!
\end{document}

after
$ pdflatex mwe

$ gs --version
9.27

$cat mwe.log
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019) (preloaded format=pdflatex 2019.8.28)  21 SEP 2019 14:00
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**mwe.tex
(./mwe.tex
LaTeX2e <2018-12-01>
(/usr/local/texlive/2019/texmf-dist/tex/latex/base/article.cls
Document Class: article 2018/09/03 v1.4i Standard LaTeX document class
(/usr/local/texlive/2019/texmf-dist/tex/latex/base/size10.clo
File: size10.clo 2018/09/03 v1.4i Standard LaTeX file (size option)
)
\c@part=\count80
\c@section=\count81
\c@subsection=\count82
\c@subsubsection=\count83
\c@paragraph=\count84
\c@subparagraph=\count85
\c@figure=\count86
\c@table=\count87
\abovecaptionskip=\skip41
\belowcaptionskip=\skip42
\bibindent=\dimen102
)
No file mwe.aux.
\openout1 = `mwe.aux'.

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 2.
LaTeX Font Info:    ... okay on input line 2.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 2.
LaTeX Font Info:    ... okay on input line 2.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 2.
LaTeX Font Info:    ... okay on input line 2.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 2.
LaTeX Font Info:    ... okay on input line 2.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 2.
LaTeX Font Info:    ... okay on input line 2.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 2.
LaTeX Font Info:    ... okay on input line 2.
[1

{/usr/local/texlive/2019/texmf-var/fonts/map/pdftex/updmap/pdftex.map}]
(./mwe.aux) ) 
Here is how much of TeX's memory you used:
 199 strings out of 492609
 2116 string characters out of 6129033
 59806 words of memory out of 5000000
 4208 multiletter control sequences out of 15000+600000
 3640 words of font info for 14 fonts, out of 8000000 for 9000
 1141 hyphenation exceptions out of 8191
 23i,4n,17p,127b,107s stack positions out of 5000i,500n,10000p,200000b,80000s
</usr/local/texlive/2019/texmf-dist/fonts/type1/public/amsfonts/cm
/cmr10.pfb>
Output written on mwe.pdf (1 page, 12039 bytes).
PDF statistics:
 12 PDF objects out of 1000 (max. 8388607)
 7 compressed objects within 1 object stream
 0 named destinations out of 1000 (max. 500000)
 1 words of extra memory for PDF output out of 10000 (max. 10000000)

**Comment by mgieseki** [comment]
This is a know issue introduced with GS 9.27. It was fixed with dvisvgm 2.7.2 (commit https://github.com/mgieseki/dvisvgm/commit/bc51951bc90b700c28ea018993bdb058e5271e9b). If you're using an older version of dvisvgm, you need an older version of Ghostscript in order to process PS and PDF files/specials.

**Comment by FLegendre** [comment]
Dear Martin,

Great ! Thanks a lot.
----
François

**Comment by mgieseki** [comment]
François, you're welcome. Feel free to report any further issues you encounter.
I'm closing this ticket here.
