### ISSUE TITLE
Use mf-nowin when available

### ISSUE THREAD

**Issue by ray851107** [mgieseki/dvisvgm#121]
The `mf` binary included in MacTeX requires XQuartz (X11 port for mac) to run, while `mf-nowin` does not. Not sure if other tex distributions includes `mf-nowin`.

**Comment by mgieseki** [comment]
Sorry, I don't have a Mac available so I can't investigate and test the required changes. Please ask the MacTeX maintainers or someone else on the TL mailing list to provide a working patch. I'll gladly apply it to the sources then.

**Comment by mgieseki** [comment]
Could you run `kpsewhich --expand-var=\$SELFAUTOLOC` in a terminal window and check if the listed directory (e.g. `/usr/local/bin`) contains dvisvgm and the `mf-nowin` binary to be used?
Unfortunately, `mf-nowin` is an optional variant that's not necessarily present in all TeX environments. The above test can probably be used to check the availability of `mf-nowin` before calling it or falling back to `mf`.

**Comment by ray851107** [comment]
> Could you run `kpsewhich --expand-var=\$SELFAUTOLOC` in a terminal window and check if the listed directory (e.g. `/usr/local/bin`) contains `dvisvgm` and the `mf-nowin` binary to be used?

Yes, they are both in `/usr/local/texlive/2019/bin/x86_64-darwin`

Output of kpsewhich:
```
$ kpsewhich --expand-var=\$SELFAUTOLOC
/usr/local/texlive/2019/bin/x86_64-darwin

```

**Comment by mgieseki** [comment]
Ok, thanks. I'll try to add a check for `mf-nowin` that will hopefully work on all platforms including TL on Mac.
