### ISSUE TITLE
pdffile special dysfunctional in 2.8.1

### ISSUE THREAD

**Issue by agrahn** [mgieseki/dvisvgm#122]
With the previous version 2.6.3 in TeXLive-19, both files below produced identical output (`dvisvgm --zoom=-1 --exact --font-format=woff`):

1 `PSfile` special
````latex
\documentclass{article}

\usepackage{kantlipsum}

\parindent=0pt

\begin{document}
\kant[1]

x\hbox to 320bp{\vrule width 0pt height 240bp\special{PSfile="example-image.eps" llx=0 lly=0 urx=320 ury=240 rwi=3200}\hss}x

\kant[2]
\end{document}
````

2 `pdffile` special 

````latex
\documentclass{article}

\usepackage{kantlipsum}

\parindent=0pt

\begin{document}
\kant[1]

x\hbox to 320bp{\vrule width 0pt height 240bp\special{pdffile="example-image.pdf" llx=0 lly=0 urx=320 ury=240 rwi=3200}\hss}x

\kant[2]
\end{document}
````
With version 2.8.1, the text after the embedded image ("x" immediately after the image and the second paragraph of lipsum)  is missing in the SVG output for the example code with `pdffile` special.

**Comment by mgieseki** [comment]
Thanks for reporting the bug. The handling of PS operators `nulldevice` and `restore` don't seem to play together correctly. I'll have a closer look tomorrow.

**Comment by agrahn** [comment]
Thanks!

**Comment by mgieseki** [comment]
You're welcome.
