### ISSUE TITLE
Issue with backslashes in pdf path on Windows

### ISSUE THREAD

**Issue by asteppke** [mgieseki/dvisvgm#123]
With the current dvisvgm 2.6.3 (from TeXLive 2019 on Windows 10) I have troubles converting a pdf file when the path contains backslashes. Quoting does not seem to help either:

````
dvisvgm --pdf C:\Users\ALEXAN~1\AppData\Local\Temp\itikz\f25feaed80c8bba5e13abae1919b249a.pdf
PostScript error: ioerror in file
Operand stack:
    C:UsersALEXAN~1AppDataLocalTempitikz♀25feaed80c8bba5e13abae1919b249a.pdf  r
````
and in quotes:
````
dvisvgm --pdf "C:\Users\ALEXAN~1\AppData\Local\Temp\itikz\f25feaed80c8bba5e13abae1919b249a.pdf"
PostScript error: ioerror in file
Operand stack:
    C:UsersALEXAN~1AppDataLocalTempitikz♀25feaed80c8bba5e13abae1919b249a.pdf  r
````
but forward slashes work:
````
dvisvgm --pdf C:/Users/ALEXAN~1/AppData/Local/Temp/itikz/f25feaed80c8bba5e13abae1919b249a.pdf
processing PDF file
  graphic size: 76.944464pt x 6.83353pt (27.042886mm x 2.401711mm)
  output written to f25feaed80c8bba5e13abae1919b249a.svg
1 of 1 page converted in 0.397 seconds
````
I saw in the release notes that in the current version 2.6.3 an issue with backslashes was fixed but this does not seem to apply here. Is there anything that can be done about this?

**Comment by mgieseki** [comment]
Thanks for reporting the issue. This is indeed a bug in the Windows version. The file path is currently passed unchanged to Ghostscript that only supports forward slashes as path separators. In case of backslashes it throws an error message. I'll fix this in the next version.
