### ISSUE TITLE
Can dvisvgm --pdf xxx.pdf support inserted pictures in the xxx.pdf?

### ISSUE THREAD

**Issue by YangLaTeX** [mgieseki/dvisvgm#127]
I use `dvisvgm --pdf xxx.pdf` to convert xxx.pdf to xxx.svg, however the pictures inserted in the original xxx.pdf are not shown in the resulting xxx.svg. I'm wondering whether dvisvgm supports to convert pictures in a pdf file or not. And if not, I hope dvisvgm can add this feature in a near future version. Many thanks!

**Comment by mgieseki** [comment]
dvisvgm doesn't yet support the conversion of bitmaps. As the implementation is tricky and I have only limited spare time to work on the utility, it's unlikely this feature will be available in the near future. I'm sorry.

**Comment by mgieseki** [comment]
Just a quick update: I've started to implement the PS `image` operator which is responsible for the processing of embedded bitmap images. You'll find the latest experimental changes in the repository. They already produce usably results but it will still take some time until the additions are ready for a new release.

**Comment by linsui** [comment]
Hi! Has png in xdv been supported in 2.11? I tried but it failed. Thanks!

**Comment by mgieseki** [comment]
Yes, it should work. Please provide a small example file that fails so that I can have a look.

**Comment by linsui** [comment]
I open a new issue #146 . Thanks!
