### ISSUE TITLE
PostScript error: undefined in run

### ISSUE THREAD

**Issue by mag911** [mgieseki/dvisvgm#128]
Would like some help with the following error:

**processing EPS file
  PostScript error: undefined in run
  Operand stack:
      --nostringval--**

$ dvisvgm --version
dvisvgm 2.8.2
Compiled without errors on bloss OS (debian 10)

Input file is a ShutterStock EPS file.
%%Title: hexagg1.eps
%%Creator: Adobe Illustrator(R) 15.0
%%CreationDate: 11/10/2016
%%BoundingBox: 0 0 300 297

Command was:
$ dvisvgm -E /mnt/share/bloss.io/ShutterStock/2020-images/6038-copy.eps

**Comment by mgieseki** [comment]
Do you use Ghostscript 9.27? This seems to be an issue with this GS version:
```
$ gs -dDELAYBIND -dNOSAFER rect.eps
GPL Ghostscript 9.27 (2019-04-04)
Copyright (C) 2018 Artifex Software, Inc.  All rights reserved.
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
see the file COPYING for details.
Error: /undefined in --run--
Operand stack:
   --nostringval--
Execution stack:
   %interp_exit   .runexec2   --nostringval--   run   --nostringval--   2   %stopped_push   --nostringval--   run   run   false   1
   %stopped_push   1991   1   3   %oparray_pop   1990   1   3   %oparray_pop
Dictionary stack:
   --dict:1031/1123(ro)(G)--   --dict:0/20(G)--   --dict:76/200(L)--
Current allocation mode is local
GPL Ghostscript 9.27: Unrecoverable error, exit code 1
```

GS 9.50 processes the same file without errors:
```
$ gs -dDELAYBIND -dNOSAFER rect.eps
GPL Ghostscript 9.50 (2019-10-15)
Copyright (C) 2019 Artifex Software, Inc.  All rights reserved.
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
see the file COPYING for details.
>>showpage, press <return> to continue<<
```
So, unfortunately, I can't do anything here. You probably need to update Ghostscript to the latest version.

**Comment by mag911** [comment]
Yes, apt reports ghostscript-9.27~dfsg-2+deb10u3

**Comment by mag911** [comment]
.. just getting ghostscript upgraded to 9.50 ..

**Comment by mag911** [comment]
Cool, 9.50 solved the problem. Thanks.
