### ISSUE TITLE
feature request: math expressions in dvisvgm:raw text

### ISSUE THREAD

**Issue by agrahn** [mgieseki/dvisvgm#130]
The `dvisvgm:raw` special accepts a number of macros, such as `{?x}` and `{?y}`, that are substituted with appropriate values during DVI to SVG conversion. In some situations, such as transformations of SVG objects, it would be desirable to make simple calculations on the substituted values. Therefore,  it would be nice to have a macro `{?...}` that accepts a mathematical expression to be evaluated and which is substituted with the expression's result in the SVG output. In the expression, it should be possible to use the variables *x* and *y* that represent the current location's coordinates.

**Comment by mgieseki** [comment]
Thanks for summarizing your feature request here. I've already a working implementation ready but it needs a bit more testing. If it works reliably on my test files, I'll push the changes.

**Comment by agrahn** [comment]
Thank you so much!

**Comment by mgieseki** [comment]
You're welcome. Even if you've found a direct solution to negate the coordinates, feel free to test the new expression `{?(...)}`.
