### ISSUE TITLE
--optimize=simplify-transform gives wrong result

### ISSUE THREAD

**Issue by agrahn** [mgieseki/dvisvgm#131]
Consider the example code `testfile.tex`:

````latex
\documentclass[12pt]{article}
\usepackage[a6paper]{geometry}

\begin{document}\Huge

some text\special{dvisvgm:raw <path d='M{?x} {?y} l40 -50' stroke='blue' />}%
\special{dvisvgm:raw <g transform='scale(-1)translate(-40,50)scale(-1)'>}%
xyz%
\special{dvisvgm:raw </g>}

\end{document}
````
After processing with
````
dvisvgm --bbox=papersize --font-format=woff --zoom=-1 --optimize=simplify-transform testfile
````
the `transform` attribute in the second special is written as ` transform='translate(40 50)'` into the SVG file, but it should be ` transform='translate(40 -50)'`.

Compare with the non-optimized SVG obtained with
````
dvisvgm --bbox=papersize --font-format=woff --zoom=-1 testfile 
````
I am using `dvisvgm-2.9`.

![img](https://user-images.githubusercontent.com/832385/77211025-d4a65a80-6b02-11ea-8bb4-757a2cb5b178.jpeg)

**Comment by mgieseki** [comment]
This is a stupid bug in the parser evaluating the `transform` commands. The long form `scale(-1,-1) translate(-40,50) scale(-1,-1)` should work as expected. I'll push the fix shortly.

**Comment by agrahn** [comment]
Thank you, Martin, for swiftly fixing this!

Also, 6005e50, the new calculator macro works like a charm! Do you think we could persuade Karl to still merge the recent changes into TL-20? Otherwise, I am looking forward to TeXLive-21 next year :-).

**Comment by kberry** [comment]
ok, in progress. i really really want this to be the last ...
