### ISSUE TITLE
Issues with beamer standard animations/transitions (\pause)

### ISSUE THREAD

**Issue by emilioj** [mgieseki/dvisvgm#134]
Hi!
I am trying to translate some PDf slides (LaTeX beamer) to svg to get advantage of the \animate package without needing a non-free PDF viewer. However, I am having some issues with standard beamer animations, in different scenarios.
This is a simple example that do not work as expected when generating the SVG:

```
\documentclass[dvisvgm,aspectratio=169]{beamer}
\setbeamertemplate{navigation symbols}{}

\begin{document}

\begin{frame}
  \begin{itemize}
  \item 1
    \pause

  \item 2
    \pause

  \item 3
    \begin{block}{foo bar}
      foo bar
    \end{block}
  \end{itemize}
\end{frame}

\end{document}
```
After `latex example.tex; latex example.tex; dvisvgm --font-format=woff --zoom=-1 -p1,- example.dvi` (I've also tried different combinations with `xelatex --no-pdf`, adding `\RequirePackage[dvips]{xcolor}` at the beginning, etc.) 3 SVG files are generated, but the beamer block is **visible** in all of them instead of only in the last one.

I am using `LaTeX-2020` and `dvisvgm 2.9.1`

Regards,
E

**Comment by mgieseki** [comment]
I guess that's an issue with the dvisvgm backend of the beamer class. If you remove `dvisvgm` from the `\documentclass` options, the dvisps backend is used which seems to work correctly.
So this is something that probably needs to be fixed by the beamer maintainers.

**Comment by emilioj** [comment]
> I guess that's an issue with the dvisvgm backend of the beamer class.

Ok, thank you very much for your quick answer. I think you are right!
Sorry for opening this issue! O:-)

I will try to manage it then with beamer maintainers :-)

Regards,
E

**Comment by mgieseki** [comment]
No problem at all. Feel free to report any issues here.
