### ISSUE TITLE
PostScript error: rangecheck in --nostringval--

### ISSUE THREAD

**Issue by xuqinghan** [mgieseki/dvisvgm#140]
process some eps （export from pdf via Acrobat Pro DC）  report error：

page 20 ( s19 ) in  ol503116q_si_001.pdf

[ol503116q_si_001.pdf](https://github.com/mgieseki/dvisvgm/files/4980017/ol503116q_si_001.pdf)

_processing EPS file
  PostScript error: rangecheck in --nostringval--
  Operand stack:
      true  --nostringval--  true  --nostringval--  --nostringval--  --nostringval--  --nostringval--  --nostringval--  --nostringval--_

**Comment by mgieseki** [comment]
I cannot reproduce the problem. The latest version of dvisvgm (2.9.1) converts the page correctly.
