### ISSUE TITLE
feature-request: Warnings to STDERR

### ISSUE THREAD

**Issue by ekaitz-zarraga** [mgieseki/dvisvgm#142]
Hi,

I've been noticing that the warnings of the 2.6.3 version of the tool are sent directly to the STDOUT and that breaks the --stdout option. This is the output I get running the tool as this:

```
cat *.dvi | dvisvgm --stdin --stdout > file.svg
reading from <stdin>
pre-processing DVI file (format version 2)
processing page 1
  graphic size: 75.630354pt x 85.757972pt (26.581029mm x 30.14048mm)
  output written to <stdout>
1 of 1 page converted in 0.154599 seconds
```

But the file is not correct SVG:

```
 *** WARNING - you have selected SAFER, indicating you want Ghostscript
               to execute in a safer environment, but at the same time
               have selected DELAYBIND. Unless you use this option with
               care (and specifically, remember to call .bindnow) it is
               possible that malicious code may be able to evade the
               limited security offered by the SAFER option.

 *** WARNING - you have selected SAFER, indicating you want Ghostscript
               to execute in a safer environment, but at the same time
               have selected WRITESYSTEMDICT. Unless you use this option with
               care and specifically, remember to execute code like:
                      "systemdict readonly pop"
               it is possible that malicious code may be able to evade the
               limited security offered by the SAFER option.
<?xml version='1.0' encoding='UTF-8'?>
<!-- This file was generated by dvisvgm 2.6.3 -->
[...]
```

It's much safer to shoot all those messages to stderr to avoid the corruption of the file and also to show the user the errors.

Maybe this is already solved in more recent versions and I'm not aware of it. Please correct me if I'm wrong.

Thanks for your time.

**Comment by mgieseki** [comment]
dvisvgm already prints its own warning and error messages to `stderr`. The warning messages you mentioned above are generated by the Ghostscript library. Unfortunately, there's no easy way to capture and redirect them. Due to many incompatible changes in the recent Ghostscript releases, dvisvgm 2.6.3 doesn't properly work together with them. So, if possible, I suggest to update dvisvgm to the latest version.

**Comment by ekaitz-zarraga** [comment]
That's the answer I was afraid of getting but it is what it is I suppose.

There's a problem with this... `dvisvgm` is often packaged inside texlive distributions so it's hard to update it by itself and all that.

Can you confirm 100% that the newest versions are capable of handling the output correctly?

Thanks for the time spent.

**Comment by mgieseki** [comment]
The changes that lead to these very warning messages were introduced with Ghostscript 9.50. dvisvgm supports this release as of version 2.8. So this special problem should go away if you either update at least to dvisvgm 2.8 or install an alternative GS release < 9.50 and tell dvisvgm to use it instead, e.g. by explicitly specifying the desired `libgs.so.X` via option `--libgs` or environment variable `LIBGS`.
However, if a future GS version introduces further incompatibilities, it might print different messages to `stdout` that will then end up in the SVG output again when using option `--stdout`.

**Comment by ekaitz-zarraga** [comment]
Thanks for the explanation. I'll close the issue.
