### ISSUE TITLE
LIBGS on OS X

### ISSUE THREAD

**Issue by PhilippImhof** [mgieseki/dvisvgm#143]
I use `dvisvgm` from TeX Live 2020 together with the additional libgs package. Now I have the following problem:

```
$ dvisvgm --pdf test.pdf
ERROR: Ghostscript is required to process PDF files
```

Version and diagnostic information:

```
$ gs --version
9.50

$ dvisvgm --version
dvisvgm 2.9.1

$ dvisvgm -h | grep gs
      --libgs=filename          set name of Ghostscript shared library

$ dvisvgm -l
bgcolor    background color special
color      complete support of color specials
dvisvgm    special set for embedding raw SVG snippets
em         line drawing statements of the emTeX special set
html       hyperref specials
papersize  special to set the page size
pdf        PDF hyperlink, font map, and pagesize specials
tpic       TPIC specials

$ export LIBGS=/usr/local/lib/libgs.dylib 
$ dvisvgm -l | grep ps
ps         dvips PostScript specials

$ ls -l /usr/local/lib
lrwxr-xr-x  1 root  wheel    54B 10 Okt 10:21 libgs.9.dylib@ -> /usr/local/share/ghostscript/9.50/lib/libgs.dylib.9.50
lrwxr-xr-x  1 root  wheel    54B 10 Okt 10:21 libgs.dylib@ -> /usr/local/share/ghostscript/9.50/lib/libgs.dylib.9.50

```

As I understand, `dvisvgm`should automatically find the library as discussed in https://github.com/mgieseki/dvisvgm/issues/66. Yet, it does not work for me. Any help would be appreciated.

**Comment by mgieseki** [comment]
Unfortunately, I don't have Mac available to reproduce the issue. What's your output of `dvisvgm -V1`? If the proper version of Ghostscript is listed there, I fear someone has to debug the corresponding code on a Mac.

**Comment by PhilippImhof** [comment]
Thanks for the quick reply. 

```
$ dvisvgm -V1 | grep Ghostscript
Ghostscript: 9.50
$ unset LIBGS
$ dvisvgm -V1 | grep Ghostscript
$
```

**Comment by mgieseki** [comment]
Ok, that looks fine. Do you still get the error message mentioned above with LIBGS set?
If I understand your initial post correctly, `dvisvgm -l` shows the `ps` entry even if LIBGS is undefined. Since `dvisvgm -V1` doesn't list Ghostscript, dvisvgm probably finds a GS library but obviously can't access its functions. Do you have another libgs installed that dvisvgm might pick by default instead?

**Comment by PhilippImhof** [comment]
Oh, sorry, that was a mistake while copying&pasting stuff from the console. I corrected my initial post. 

`dvisvgm -l` only shows `ps` when `LIBGS` is set.

**Comment by mgieseki** [comment]
Ah ok, that's reassuring. Does the conversion work if LIBGS is set? If yes, the only problem is that dvisvgm doesn't find libgs by default. You should make sure that the dynamic linker looks for shared libraries in the corresponding folder.

**Comment by PhilippImhof** [comment]
Yes, everything works fine as long as `LIBGS` is set. I will try to find a fix for the search path. Thank you for your help.

**Comment by owiecc** [comment]
Should #66 be reopened? I just had a similar issue as @PhilippImhof

**Comment by mgieseki** [comment]
I think, this isn't an issue with dvisvgm. If libgs is not linked during build time, dvisvgm tries to open it using the `dlopen` mechanism of the operating system – except you directly point to it by setting `LIBGS` or `--libgs`. On Mac OS, it currently looks for `libgs.so.N`, `libgs.dylib.N`, and `libgs.N.dylib`, where _N_ ≥ 7 is the soversion of the library. If one of the library files is present but can't be found automatically, you probably have to add the library folder to the configuration file of the dynamic linker (`/etc/ld.so.conf` on Linux). The alternative is to use `LIBGS` or `--libgs`.

**Comment by owiecc** [comment]
Then may I suggest amending the `processing of PostScript specials is disabled (Ghostscript not found)` error with a suggestion on how to fix it. Something in the tone: 

> Ghostscript not found. Please install ghostscript. If ghostscript is installed then provide the path to libgs library either by setting the environment variable LIBGS=/path/to/libgs.x.xx.dylib or pass the path explicitly --libgs=/path/to/libgs.x.xx.dylib

That will help debugging this specific issue.
