### ISSUE TITLE
Virtual font fallback to Japanese tfm

### ISSUE THREAD

**Issue by t-tk** [mgieseki/dvisvgm#144]
Hallo, Thank you for developing dvisvgm.

I have proposed new feature of virtual font which designates Japanese TFMs.
https://github.com/texjporg/tex-jp-build/issues/99
Recently, I have applied patches to support the function on dvipdfmx and dvips and released some packages to use it.
If it is possible, please consider to support the fallback feature by dvisvgm.

Thanks.

---
(Summary)
I propose a new rule:
If a virtual font has no entry of a codepoint and the first MAPFONT designates (u)pTeX JFM,
we designate the glyph of the same codepoint in the TFM(JFM) with the smallest font ID.
The new rule helps to shrink size of Japanese virtual fonts.

For example, conventionally `upphiraminw3-h.ovp` starts with
```
(MAPFONT D 1
   (FONTNAME uphminr-h)
   (FONTCHECKSUM O 0)
   (FONTAT R 1.000000)
   (FONTDSIZE R 10.000000)
   )
```
and a huge volume of entries for fullwidth characters continue such as:
```
(CHARACTER H 2F9F4
   (CHARWD R 1.000000)
   (MAP
      (SETCHAR H 2F9F4)
      )
   )
```

Conventionally, if the virtuanfont lacks an entry of a CHARACTER 0xXXXXX, dviware rejected.
My proposal is to introduce the new rule to interpret as the fullwidth CHARACTER 0xXXXXX of `uphminr-h`:
```
(CHARACTER H XXXXX
   (CHARWD R 1.000000)
   (MAP
      (SETCHAR H XXXXX)
      )
   )
```

---
References:
dvipdfmx:
https://www.tug.org/svn/texlive?view=revision&revision=54319  (patch)
https://www.tug.org/svn/texlive?view=revision&revision=54979  (test data)

dvips:
https://www.tug.org/svn/texlive?view=revision&revision=54794  (patch)
https://www.tug.org/svn/texlive?view=revision&revision=55085  (test data)
https://www.tug.org/svn/texlive?view=revision&revision=55217  (document)

**Comment by mgieseki** [comment]
I guess I can adapt the code so that it handles your proposal. It actually shouldn't be too complicated. I'll have a look.

**Comment by mgieseki** [comment]
I have a first working implementation but noticed, that character 20B9F (𠮟) is missing when converting `upjf.dvi` from the [dvipdfmx test data](https://www.tug.org/svn/texlive?view=revision&revision=54979). It turns out that the character is not mapped by `UniJIS-UTF16-H` and is therefore replaced by the `.notdef` character. However, dvipdfmx does show the character correctly. Is there a special rule how to handle unmapped characters here?

SVG:
![SVG](https://user-images.githubusercontent.com/3620467/99276836-5fc02780-282d-11eb-8c0c-a440d6d54caa.png)
PDF: 
![PDF](https://user-images.githubusercontent.com/3620467/99276913-78c8d880-282d-11eb-8231-4c72b6220cf3.png)

**Comment by t-tk** [comment]
Thank you for your trial.
U+20B9F is a character over BMP and the typeout command in upTeX dvi file is `SET3` (0x82) followed by the character code 0x020B9F.
dvipdfmx convert the codepoint to a surrogate pair (0xD842 0xDF9F) at https://github.com/texjporg/tex-jp-build/blob/ebd8e5e51cb1e3ad1a8400c5abdca733cb149b85/source/texk/dvipdfm-x/dvi.c#L1355-L1362 and https://github.com/texjporg/tex-jp-build/blob/ebd8e5e51cb1e3ad1a8400c5abdca733cb149b85/source/texk/dvipdfm-x/dvi.c#L1433-L1440

I hope if it meight be a hint for your question.

**Comment by mgieseki** [comment]
Thank you for your feedback. I'm still not sure how to treat character 20B9F here.
According to `upjf.map`, the fonts `upjf-r` and `upjf-r` (referenced by `upjf.vf`) are CID-based fonts mapped by `UniJIS-UTF16-H`:
```
upjf-r  UniJIS-UTF16-H  HaranoAjiMincho-Regular.otf
upjf-g  UniJIS-UTF16-H  HaranoAjiGothic-Regular.otf
```
So, the character codes given in the DVI file must be looked up in the CMap file. However, there's no entry for CID 20B9F in `UniJIS-UTF16-H` which means that it is considered undefined (according to the Adobe CMap specification).
Do you know why dvipdfmx nonetheless interprets character 20B9F as Unicode point and doesn't treat it as undefined? Is there a special rule that defines a fallback for unmapped CIDs?

**Comment by t-tk** [comment]
As you mentioned,
UniJIS-UTF16-H designate the surrogate pair 0xD842 0xDF9F for U+20B9F to CID 13803.
https://github.com/adobe-type-tools/cmap-resources/blob/199e2e91bacc4cd37ddbf65f5a2d13b4766673db/Adobe-Japan1-7/CMap/UniJIS-UTF16-H#L13139
