### ISSUE TITLE
cannot convert pdf - generates empty svg output but no error

### ISSUE THREAD

**Issue by cobordism** [mgieseki/dvisvgm#145]
I tried to compile 2.10.1 on debian-10 (in qubesOS).

The end result is that `dvisvgm --pdf`  generates empty svgs (i.e. 0pt x 0pt, see below) but there is no discernible error message - not even at verbosity 7. 

Where do I go to find out more about what is going on?

```
$ /usr/local/bin/dvisvgm --version
dvisvgm 2.10.1


user@manim:~/Documents/renderings/Tex$ /usr/local/bin/dvisvgm  -V1
dvisvgm 2.10.1 (x86_64-pc-linux-gnu)
------------------------------------
brotli:      1.0.9
clipper:     6.2.1
fontforge:   20160721
freetype:    2.9.1
Ghostscript: 9.27
kpathsea:    6.3.1/dev
potrace:     1.16
xxhash:      0.8.0
zlib:        1.2.11


user@manim:~/Documents/renderings/Tex$ /usr/local/bin/dvisvgm  -l
bgcolor    background color special
color      complete support of color specials
dvisvgm    special set for embedding raw SVG snippets
em         line drawing statements of the emTeX special set
html       hyperref specials
papersize  special to set the page size
pdf        PDF hyperlink, font map, and pagesize specials
ps         dvips PostScript specials
tpic       TPIC specials


user@manim:~/Documents/renderings/Tex$ /usr/local/bin/dvisvgm --pdf -s   ./ce5f349362954af9.pdf
processing PDF file
<?xml version='1.0' encoding='UTF-8'?>
<!-- This file was generated by dvisvgm 2.10.1 -->
<svg version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='0pt' height='0pt' viewBox='0 0 0 0'>
<g id='page1'/>
</svg>  graphic size: 0pt x 0pt (0mm x 0mm)
  output written to /
1 of 1 page converted in 0.087815 seconds
```

**Comment by zvezdochiot** [comment]
https://tug.org/texinfohtml/dvips.html

**Comment by cobordism** [comment]
Thank you @zvezdochiot for your quick response. 

Can you elaborate just a little bit?

**Comment by mgieseki** [comment]
That's hard to tell without further information. Does this happen with all PDF files or just selected ones? Does Ghostscript process the PDF file correctly when you call is like this?
```
gs -dDELAYBIND -dNOSAFER -dLastPage=1 myfile.pdf
```

**Comment by cobordism** [comment]
The tex contains just the letter a:

```
user@manim:~/Documents/renderings/Tex$ cat test.tex
\documentclass[preview]{standalone}

\usepackage[english]{babel}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{dsfont}
\usepackage{setspace}
\usepackage{tipa}
\usepackage{relsize}
\usepackage{textcomp}
\usepackage{mathrsfs}
\usepackage{calligra}
\usepackage{wasysym}
\usepackage{ragged2e}
\usepackage{physics}
\usepackage{xcolor}
\usepackage{microtype}
\DisableLigatures{encoding = *, family = * }
\linespread{1}

\begin{document}

\begin{center}
a
\end{center}

\end{document}
```

I run pdflatex to get test.pdf.  The pdf looks fine when opened in pdf viewer.

Then:

```
user@manim:~/Documents/renderings/Tex$ /usr/local/bin/dvisvgm --pdf -s -n -v 7  ./test.pdf 
processing PDF file
<?xml version='1.0' encoding='UTF-8'?>
<!-- This file was generated by dvisvgm 2.10.1 -->
<svg version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='0pt' height='0pt' viewBox='0 0 0 0'>
<g id='page1'/>
</svg>  graphic size: 0pt x 0pt (0mm x 0mm)
  output written to /
1 of 1 page converted in 0.0844669 seconds
```

but
```
user@manim:~/Documents/renderings/Tex$ gs -dDELAYBIND -dNOSAFER -dLastPage=1 ./test.pdf 
GPL Ghostscript 9.27 (2019-04-04)
Copyright (C) 2018 Artifex Software, Inc.  All rights reserved.
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
see the file COPYING for details.
Processing pages 1 through 1.
Page 1
%%BoundingBox: 169 0 175 5
%%HiResBoundingBox: 169.685995 0.000000 174.275995 4.284000
>>showpage, press <return> to continue<<
```

**Comment by cobordism** [comment]
I found something.
When I remove the line `\usepackage[T1]{fontenc}` from the tex source, it works.

This is strange, because that line is part of the standard manim template and nobody else has any problems (using dvisvgm bundled with ubuntu20.04 or MacOS Texlive ...)

Does that help?

**Comment by mgieseki** [comment]
Yes, that explains the issue. If you add `\usepackage[T1]{fontenc}`, pdflatex embeds bitmap fonts into the pdf file. These are not supported by dvisvgm's PDF module. Instead, you can use `latex` rather than `pdflatex` and convert the resulting DVI with dvisvgm. Now the characters are vectorized which should lead to a proper SVG file.

**Comment by cobordism** [comment]
The problem is that some of the tex we use doesn't compile correctly to dvi - that why I had been using the pdf option.

The exact same tex files worked on ubtuntu 20.04 using dvisvgm --pdf. So why won't they work here?

**Comment by mgieseki** [comment]
Maybe there are vector variants of the fonts installed and therefore used by pdflatex instead of the PK fonts. In some TeX environments the EC font family is mapped to LM (lmodern) fonts which are available in vector format. You can zoom into the PDF files and check if the letters look jaggy or smooth. The jaggy bitmaps can't be processed by dvisvgm. I doubt that they are on some systems.

**Comment by cobordism** [comment]
Thank you for taking the time to respond to me. 
I can investigate more with fonts. However I feel that it can't just be the fonts.

Let me tell you some more context. The reason I have been using pdf instead of dvi is because I wanted to use the chalkduster font: https://graphicdesignfonts.com/chalkduster-font/
I can install this font on my system and use lualatex to compile it to a pdf, but I cannot get a working dvi.

This exact same font has worked for me on ubuntu (and indeed I made videos using manim with it https://vimeo.com/user32587255)

**Comment by mgieseki** [comment]
Please let me know if you find any further hints. I suggest to try converting the exact same PDF files linked above on your Ubuntu machine. Also create the PDF files there again -- especially the one with fontenc T1 given -- and see if the results differ.

DVI files created by LuaLaTeX are not fully supported yet since they need some changes in LuaTeX which will probably come with the next TeX Live release. However, XeLaTeX also handles native/system fonts and dvisvgm can process the extended DVI files (`.xdv`) files created by `xelatex -no-pdf`. Maybe that's an alternative route.

**Comment by cobordism** [comment]
thanks.
I'll report back.

**Comment by cobordism** [comment]
The exact same pdf file on ubuntu:
```
cobordism@lungo:~/Desktop$ dvisvgm --pdf -n ./6d83ac5bdf0d8751.pdf 
processing PDF file
  graphic size: 344.999916pt x 20.343001pt (121.253603mm x 7.149747mm)
  output written to 6d83ac5bdf0d8751.svg
1 of 1 page converted in 0.613816 seconds
cobordism@lungo:~/Desktop$ dvisvgm --pdf -n ./6d83ac5bdf0d8751.pdf -V1
dvisvgm 2.8.1 (x86_64-pc-linux-gnu)
-----------------------------------
brotli:      1.0.7
clipper:     6.2.1
fontforge:   20160721
freetype:    2.10.1
Ghostscript: 9.50
kpathsea:    6.3.1
potrace:     1.16
xxhash:      0.7.2
zlib:        1.2.11
cobordism@lungo:~/Desktop$ dvisvgm --pdf -n ./6d83ac5bdf0d8751.pdf -l
bgcolor    background color special
color      complete support of color specials
dvisvgm    special set for embedding raw SVG snippets
em         line drawing statements of the emTeX special set
html       hyperref specials
papersize  special to set the page size
pdf        PDF hyperlink, font map, and pagesize specials
ps         dvips PostScript specials
tpic       TPIC specials
```

**Comment by cobordism** [comment]
but 
```
cobordism@lungo:~/Desktop$ dvisvgm --pdf -n ./test2.pdf 
processing PDF file
  graphic size: 344.999916pt x 4.305084pt (121.253603mm x 1.513064mm)
  output written to test2.svg
1 of 1 page converted in 0.0824699 seconds
cobordism@lungo:~/Desktop$ dvisvgm --pdf -n ./test.pdf 
processing PDF file
  graphic size: 0pt x 0pt (0mm x 0mm)
  output written to test.svg
1 of 1 page converted in 0.0828431 seconds
```

**Comment by mgieseki** [comment]
Ok, so these are probably two different issues. The bitmap fonts are obviously not processed on Ubuntu either. Does GS 9.27 on Debian show any errors errors when calling `gs -dDELAYBIND -dNOSAFER -dLastPage=1 6d83ac5bdf0d8751.pdf`?
If so, do you get a different output with GS 9.50 on Ubuntu? If I remember correctly, there was a font bug in GS 9.27 that lead to errors when using `DELAYBIND`.

BTW, you can omit option `-n`. It has no effect when converting PS or PDF files.

**Comment by cobordism** [comment]
On Ubuntu:
```
cobordism@lungo:~/Desktop$ gs -dDELAYBIND -dNOSAFER -dLastPage=1 6d83ac5bdf0d8751.pdf
GPL Ghostscript 9.50 (2019-10-15)
Copyright (C) 2019 Artifex Software, Inc.  All rights reserved.
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
see the file COPYING for details.
Processing pages 1 through 1.
Page 1
>>showpage, press <return> to continue<<
```
and a window opens correctly showing the pdf. Will reboot into qubes/debian and update this comment. Just a moment...

**Comment by mgieseki** [comment]
As supposed, GS 9.27 causes the issue here. It fails processing your file and therefore can't deliver the required graphics data to dvisvgm. As a result, you get an empty SVG file. The only way to work around this is to update GS to a more recent version.

**Comment by cobordism** [comment]
Thank you for your help! :100:

**Comment by mgieseki** [comment]
You're welcome!

**Comment by louisstuart96** [comment]
Well, I'm facing the same issue:
I'm using `dvisvgm` version 2.13.3 bundled in TeX Live 2022, on macOS 12.4(Apple M1):
```
$ dvisvgm -V1
dvisvgm 2.13.3
--------------
brotli:      1.0.9
clipper:     6.2.1
fontforge:   20160721
freetype:    2.11.1
Ghostscript: 9.56.1
kpathsea:    6.3.4
potrace:     1.16
xxhash:      0.8.1
zlib:        1.2.11

$ dvisvgm -l
bgcolor    background color special
color      complete support of color specials
dvisvgm    special set for embedding raw SVG snippets
em         line drawing statements of the emTeX special set
html       hyperref specials
papersize  special to set the page size
pdf        PDF hyperlink, font map, and pagesize specials
ps         dvips PostScript specials
tpic       TPIC specials
```

I've also installed GhostScript 9.56.1 via `Homebrew`, and exported `LIBGS` environment.

Currently I cannot convert any PDF to SVG via `dvisvgm --pdf`, even PDF generated by this MWE resulted in empty (0x0) SVG:
```tex
\documentclass[a4paper,10pt]{article}
% Package goes here
\pagestyle{empty}
\begin{document}
Test Page.
\end{document}
```

```
$ gs -dDELAYBIND -dNOSAFER -dLastPage=1 -dBATCH -dNOPAUSE simple.pdf
GPL Ghostscript 9.56.1 (2022-04-04)
Copyright (C) 2022 Artifex Software, Inc.  All rights reserved.
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
see the file COPYING for details.
Processing pages 1 through 1.
Page 1
%%BoundingBox: 140 704 185 713
%%HiResBoundingBox: 140.111996 704.069979 184.463994 712.925978

$ dvisvgm --pdf -s simple.pdf
processing PDF file
<?xml version='1.0' encoding='UTF-8'?>
<!-- This file was generated by dvisvgm 2.13.3 -->
<svg version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='0pt' height='0pt' viewBox='0 0 0 0'>
<g id='page1'/>
</svg>  graphic size: 0pt x 0pt (0mm x 0mm)
  output written to /
1 of 1 page converted in 0.154806 seconds
```
I've tried adding option `--libgs=/opt/homebrew/lib/libgs.dylib`, but it won't solve the problem.

**Comment by mgieseki** [comment]
That's caused by the activation of Ghostscript's new PDF interpreter as of version 9.56.1. 
See the comments in https://github.com/mgieseki/dvisvgm/issues/183 for further information.
