### ISSUE TITLE
Text in custom font has wrong encode is svg

### ISSUE THREAD

**Issue by linsui** [mgieseki/dvisvgm#147]
The tex file is

```tex
\documentclass[margin=3pt,dvisvgm]{standalone}

\usepackage{fontspec}

\begin{document}
\newfontfamily\arial{Arial}
\arial abcde
\end{document}
```

I generate the svg with

```
xelatex -no-pdf test
dvisvgm --zoom=-1 --exact --font-format=woff test.xdv
```

The result looks well, however if I copy the text from the svg I get `ΤΥΦΧΨ`. Pdf generated by xelatex is correct.

**Comment by mgieseki** [comment]
The issue is caused by an ambiguity in the mapping table that maps glyph indices to code points. It's easy to fix. I'm going to commit a patch shortly.

**Comment by linsui** [comment]
Thanks!
