### ISSUE TITLE
Color conversion problem ?

### ISSUE THREAD

**Issue by mb4e** [mgieseki/dvisvgm#149]
Hello, I am trying to convert the following pdf file, which was made with pdflatex and tkz-tab. 

[048e08463786ae89f05faff5ec72673f25f16196.pdf](https://github.com/mgieseki/dvisvgm/files/6175173/048e08463786ae89f05faff5ec72673f25f16196.pdf)

Using version 2.9.1of dvisvgm, supplied with Texlive 2020, I get the following svg file (converted to png because I can't join svg files), in which the background color of the table is not correctly rendered.

`$ dvisvgm --pdf 048e08463786ae89f05faff5ec72673f25f16196.pdf`

![048e08463786ae89f05faff5ec72673f25f16196](https://user-images.githubusercontent.com/274317/111865100-58d52d00-8965-11eb-9706-c2f8204d9645.png)

Thanks for the work.

**Comment by mgieseki** [comment]
Yes, that's an issue with version 2.9.1 and earlier related to PDF operators `B` and `B*`. It has been fixed in dvisvgm 2.10. If you update to the latest release, the file should be converted correctly.

**Comment by mb4e** [comment]
Thanks a lot, I just have to wait for the update to be carried out at Texlive level, which for the moment still provides version 2.9.1.

**Comment by mgieseki** [comment]
If you happen to use TeX Live on Windows, you can get a recent version of dvisvgm from the [W32TeX site](http://w32tex.org). Otherwise, you need to build it on your own or actually wait for the upcoming next TL release.

**Comment by mb4e** [comment]
No problem, thanks again.

**Comment by mgieseki** [comment]
Since the problem seems to be resolved, I close the ticket. Feel free to report any further issues you encounter.
