### ISSUE TITLE
configure: error: libkpathsea not found, please install the corresponding package first

### ISSUE THREAD

**Issue by scrouthtv** [mgieseki/dvisvgm#151]
Hello,

I am currently trying to compile `dvisvgm` from source using system libraries. I installed all dependencies (especially `texlive-bin`).

Both `/usr/bin/kpsewhich` and `/usr/include/kpathsea` exist.

However, if I download `dvisvgm-2.11.1.tar.gz`, extract and run `./configure`, I get:
```
bla bla
checking whether termios.h defines TIOCGWINSZ... no
checking whether sys/ioctl.h defines TIOCGWINSZ... yes
checking kpathsea/kpathsea.h usability... yes
checking kpathsea/kpathsea.h presence... yes
checking for kpathsea/kpathsea.h... yes
checking for kpse_find_file in -lkpathsea... no
configure: error: libkpathsea not found, please install the corresponding package first
```

Do you have any idea what might be going on here?

**Comment by mgieseki** [comment]
Is `libkpathsea.a` or `libkpathsea.so` present in the search path of the linker? As far as I know, TL links all binaries statically and doesn't ship `libkpathsea` separately.

**Comment by scrouthtv** [comment]
Weird. I just set up a new container and it works this time. `libkpathsea.so.6` is also in the output of `ldconfig -v`. I don't know what's going on here. I'll report back if I see anything.
