### ISSUE TITLE
Stem plot marker missing when converting from PDF

### ISSUE THREAD

**Issue by Krasjet** [mgieseki/dvisvgm#152]
The PDF mode of `dvisvgm` seems to have some problem rendering the `*` marker of pgfplots.

A minimal working example is as follows
```tex
\documentclass{standalone}
\usepackage{pgfplots}

\begin{document}
\begin{tikzpicture}
  \begin{axis}[
    axis x line=middle, axis y line=middle,
    height=4cm, width=8cm,
    xmax=6, xmin=-6, ymax=1.2, ymin=-1.2,
    ticks=none
  ]
  \addplot[domain=-5:5, thick, ycomb, mark=*, samples=10] {sin(deg(2*pi*x))};
  \end{axis}
\end{tikzpicture}
\end{document}
```
If you try to compile it to a `pdf` and then convert it to SVG
```console
$ latexmk -pdf stem.tex
$ dvisvgm -P stem.tex
```
the markers will be missing from the output SVG image:

![](https://0x0.st/-Tun.svg)

whereas the correct rendering should be 
![stem-1](https://user-images.githubusercontent.com/5229241/114285007-dc90af80-9a21-11eb-8154-a02009f60d54.png)

However, converting from DVI does not have this problem, but I need to use XeLaTeX and it only compiles to XDV files. Somehow `dvisvgm` doesn't work very well with XDV files. Compiling it
```console
$ latexmk -xelatex stem.tex
$ dvisvgm stem.xdv
```
produces an empty SVG file, so my only option is to use PDF.

Do you have any idea what might have caused the problem?

My versions are
```console
$ dvisvgm --version
dvisvgm 2.9.1
$ gs --version
9.54.0
```
Here are some example outputs:

- [`stem.pdf`](https://github.com/mgieseki/dvisvgm/files/6290804/stem.pdf)
- [`stem.svg`](https://0x0.st/-Tun.svg)
- [`stem.xdv`](https://0x0.st/-TSr.xdv)

**Comment by mgieseki** [comment]
This issue has already been fixed in dvisvgm 2.10. (see #139). It's caused by changes introduced with Ghostscript 9.52 which was released after dvisvgm 2.9.1 (the version you're using). So, you could either update to a newer release of dvisvgm if possible, or install an older version of Ghostscript alongside the recent one.

**Comment by Krasjet** [comment]
Thanks, upgrading `dvisvgm` does fix the missing marker problem, but converting `xdv` still gives an empty SVG file. Is there anything I need to add to make `xdv` conversion working?

**Comment by mgieseki** [comment]
By default, pgf creates pdf specials when used with XeTeX which dvisvgm doesn't support. You can add documentclass option `dvisvgm` to request dvisvgm specials instead:
```latex
\documentclass[dvisvgm]{standalone}
...
```
Option `dvips` would be another possibility but as far as I see, pgf doesn't like it in conjunction with XeTeX.

**Comment by agrahn** [comment]
You can force `pgfplots` and `pgf` to use the `dvips` driver:

```latex
\documentclass{standalone}
\def\pgfsysdriver{pgfsys-dvips.def}
\usepackage{pgfplots}

\begin{document}
\begin{tikzpicture}
  \begin{axis}[
    axis x line=middle, axis y line=middle,
    height=4cm, width=8cm,
    xmax=6, xmin=-6, ymax=1.2, ymin=-1.2,
    ticks=none
  ]
  \addplot[domain=-5:5, thick, ycomb, mark=*, samples=10] {sin(deg(2*pi*x))};
  \end{axis}
\end{tikzpicture}
\end{document}
````

Then run `xelatex --no-pdf` to get an `xdv` with only PS `\specials`.

**Comment by Krasjet** [comment]
Somehow these options produces glitches for the PDF output of another diagram I have, but it's probably a pgf and xetex compatibility issue.

I'll close this issue for now. Thank you very much for your help.
