### ISSUE TITLE
Loss of text when converting an EPS file

### ISSUE THREAD

**Issue by fjwright** [mgieseki/dvisvgm#153]
When I try to convert this EPS file (zipped for upload), [gnuplotex1.zip](https://github.com/mgieseki/dvisvgm/files/6305086/gnuplotex1.zip), the conversion runs with no error messages but the resulting SVG file is missing all the text annotations. Ghostscript and GIMP both open the EPS file and display it correctly, complete with text. This is the command that I ran on Cygwin and the resulting output:
```
$ dvisvgm -E -o tmp gnuplotex1.eps
processing EPS file
  graphic size: 617.30625pt x 462.72875pt (216.958333mm x 162.630556mm)
  output written to tmp.svg
file converted in 0.452221 seconds

$ dvisvgm --version=yes
dvisvgm 2.11.1
--------------
brotli:      1.0.9
clipper:     6.2.1
fontforge:   20160721
freetype:    2.10.4
Ghostscript: 9.53.3
kpathsea:    6.3.3
potrace:     1.16
xxhash:      0.8.0
zlib:        1.2.11
```

**Comment by mgieseki** [comment]
Sorry, the EPS file is way to big to trace down the issue. If possible, please reduce it to just a few (missing) characters and remove the graphics that convert correctly. Unfortunately, I currently don't have the time to do that myself.

**Comment by mgieseki** [comment]
I just found the reason for the missing characters: The EPS file references an embedded Type 3 bitmap font which is used to typeset the characters. dvisvgm only supports vector fonts and ignores all characters belonging to a bitmap font.

**Comment by fjwright** [comment]
Thanks for the explanation. I think it would be helpful if dvisvgm output a warning message rather than silently ignoring bitmap fonts.

**Comment by mgieseki** [comment]
I'll have a look but I guess it's not an easy task. The PostScript code is processed by Ghostscript and it only tells dvisvgm that it's processing a glyph. It doesn't distinguish between vector and bitmap glyphs. If the glyph doesn't produce any path segments, it might be a bitmap but it could also be an "empty" glyph representing a whitespace character for example. 
I have to dig a bit deeper into this.

**Comment by mgieseki** [comment]
After having a closer look into Ghostscript and its API, I haven't found a viable way to determine whether the glyph to be drawn consists of bitmap or vector data. So, unfortunately, dvisvgm can't output warnings about potentially missing glyphs in the generated SVG files.

**Comment by fjwright** [comment]
OK. Thanks for pursuing this and for letting me know the outcome.

Francis
