### ISSUE TITLE
Consider to fix language errors

### ISSUE THREAD

**Issue by hpreusse** [mgieseki/dvisvgm#159]
Our fine languaguage checker in Debian identified some improvements in the documentation. We created [a patch](https://raw.githubusercontent.com/debian-tex/dvisvgm/master/debian/patches/spelling_errors_in_manual_page) for this, consider to copy it from our system. Thanks!

**Comment by mgieseki** [comment]
Thanks for linking the patch. I'll have a look. Since the manual page is generated from an AsciiDoc file, the changes must be incorporated there.
