### ISSUE TITLE
Any option to output svg without <use> element or any <..id..>?

### ISSUE THREAD

**Issue by jhx000** [mgieseki/dvisvgm#163]
I wonder if dvisvgm has any command option to output the svg without <use> element or any <..id..>.

Case 1:
When export equations from latex or diagrams from Tikz to svg by dvisvgm, I found that individual equations have <use> elements that refer to the paths in the <def> cache. And different svgs may have same id that leads to id conflict in same html page.

Case 2:
The backend article editor of one publisher platform does not support svg with element id. When I embed the svg in the article, the editor will automatically remove element id from the svg. It leads to mass of my science article. It will save a lot of time if dvisvgm had the output switch option.

I tried to use inkscape process the svg output from dvisvgm by ungroup all and save to plain svg file. It works for some case. But the downside is: 1. very slow to batch process, 2. inkscape is a bit heavy in latex toolchain.

I know Mathjax has a option "useGlobalCache: false" and "useFontCache: false" to controls whether the SVG output repeat paths every time rather than use <use> elements to re-use paths .  But I prefer to use dvisvgm in my latex toolchain.

Any idea or suggestion is appreciated.

**Comment by mgieseki** [comment]
If you're just talking about `use` elements created by command line option `--no-fonts`, you can add argument  `1` to this option. It tells dvisvgm to only create `path` and no `use` elements (also see the [manual page](https://dvisvgm.de/Manpage/#opt-no-fonts)). All other `id` attributes are required to implement the desired functionality, like patterns, hyperlinks, and clipping paths. They can't be avoided easily.
You could also write a simple XSLT or Python script to replace the IDs by different ones to prevent collisions across different SVG files. There's currently no option to do this directly with dvisvgm.

**Comment by jhx000** [comment]
Thank you so much! It works. Everything goes well with argument 1.

**Comment by mgieseki** [comment]
Great, I'm glad to hear that your issue could be solved so easily.
