### ISSUE TITLE
Depth message for xdv.

### ISSUE THREAD

**Issue by jhx000** [mgieseki/dvisvgm#164]
When processing dvi from latex, dvisvgm prints a message showing the assigned width, height, and depth values in TEX point units.
>latex test1.tex
>dvisvgm --no-fonts=1 test1.dvi -p 1- -o %f-%p.svg

But when processing xdv from xelatex, it seemed that dvisvgm does not print the depth information and only width and height is shown.
>xelatex --no-pdf test2.tex
>dvisvgm --no-fonts=1 test2.xdv -p 1- -o %f-%p.svg

In the test1 and test2 tex files, preview package with tightpage option is activated.

Anything I missed to get the depth info for xdv from xelatex?

**Comment by mgieseki** [comment]
The preview package doesn't write any extent values to the XDV file, so dvisvgm can't evaluate them. It's probably not designed to work with XeTeX because the latter mainly creates PDF files while the preview package is based on PostScript.

**Comment by jhx000** [comment]
Got it. Any idea on how to align svg generated by xdv with text in html without depth info?

**Comment by mgieseki** [comment]
I don't think it's possible without the depth information. You could add some code to your LaTeX file that prints the depth to the console when compiling it, e.g. something like this:
```tex
\newsavebox{\mybox}
\sbox{\mybox}{This is my text}
\typeout{depth=\the\dp\mybox}
```
I'd also suggest to ask the developer of the preview package if he could add an option to put the PS-based box values (or a separate `\special` providing the data) into the XDV file.

**Comment by jhx000** [comment]
Thanks. I will try it.

**Comment by jhx000** [comment]
Hi, Martin:
  When I tried to use xelatex+dvisvgm to get svg from xdv with depth from
\sbox, almost all worked except \mathbf{}, \mathrm{}, \cos, \sin. Other
such as \sum_{i=1}^{n} a_i etc all work well. Only  \mathbf{}, \mathrm{},
\cos, \sin, maybe other trigonometry went wrong.
  Thus, the test.html file from xelatex shows the svg in wrong depth for
above four math elements.
  I tried by latex+dvisvgm to get svg from dvi with depth from \sbox,
everything is correct.
  When I review the svg files from xelatex, I found the svg shown in
browser is not top aligned while those svg files from latex shown in brower
is top aligned. I am not sure if it is related.
  I also tried xelatex + dvisvgm "--pdf" option (pdf to svg), the depth is
correct but the width is wrong. I knew that you will not invest time on pdf
option. So I did not attached the related files of pdf option.

 Attached file:
  pdflatex
--test.command.txt  commands I run the test
--test.html                output html file
--tex2svg.dvi            output dvi file
--tex2svg.tex            the tex file
--tex2svg_depth.txt  depth information from sbox
--tex2svg_?.svg        output svg files

  xelatex
--test.command.txt  commands I run the test
--test.html                output html file
--tex2svg.xdv           output xdv file
--tex2svg.tex            the tex file
--tex2svg_depth.txt  depth information from sbox
--tex2svg_?.svg        output svg files

  Please kindly shot some light on the puzzle.
Thanks in advance.

Best regards,

Jay

Martin Gieseking ***@***.***> 于2021年11月20日周六 上午2:38写道：

**Comment by muzimuzhi** [comment]
@jhx000 Your attachments are missing because Github only accepts attachments added from web.
