### ISSUE TITLE
Question: How to produce a series of SVG files from a multipage EPS file?

### ISSUE THREAD

**Issue by pstricks-fans** [mgieseki/dvisvgm#167]
Given a trivial PSTricks file named `input.tex` as follows.

```
\documentclass[pstricks,border=1cm]{standalone}
\usepackage{amsmath}
\begin{document}
\foreach \a in {0,10,..., 350}{%
\begin{pspicture}[showgrid](-5,-5)(5,5)
		\pscircle{5}
		\rput(0,0){$\int_a^bf(x)\,\mathrm{d}x$}
		\rput(5;\a){\rput{\a}(0,0){\psline[linecolor=red]{->}(-12pt,0)}}
\end{pspicture}}
\end{document}
```

I compile with the following command:

```
latex input.tex
dvips -E -t unknown -o input.eps input.dvi
dvisvgm --eps --no-fonts --bbox=papersize --precision=1 --page=- --output=output-%3p.svg input.eps
```

But I only get one SVG file that superimposes all the pages of the EPS file.

I want to have an SVG file for each page of the EPS file. How to do so?

**Comment by mgieseki** [comment]
That's not possible because EPS is a single-page format. PS operators required to define multiple pages are not allowed in valid EPS files. So you have to split the PS file into separate EPS files consisting of one page only and convert them separately.
