### ISSUE TITLE
dvisvgm 2.11.1 crashes on Solaris 11.4

### ISSUE THREAD

**Issue by joachim42** [mgieseki/dvisvgm#170]
We are using the latest version of TexLive, which includes dvisvgm 2.11.1, on Solaris 11.4, patchlevel 11.4.38.101.6 (the latest one).
dvisvgm gives the following error:

$ /moodle/tools/texlive/2021-11-24/bin/x86_64-solaris/dvisvgm -E beispiel.ps -o beispiel.svg
processing EPS file
  graphic size: 100.375pt x 18.0675pt (35.277778mm x 6.35mm)
  output written to beispiel.svg
file converted in 0.526434 seconds
Segmentation Fault (core dumped)

The output file looks OK, but after creating it, the program crashes.
On a test VM the error does not occur. The dvisvgm binary is identical, it has the same version number and the same checksum:

$ cksum dvisvgm
1610221261 7172848 dvisvgm

The test VM however does not get any patches, so it has an old patchlevel: 11.4.0.15.0
Is it possible that this is the reason, i. e., dvisvgm does not work on newer Solaris versions?

**Comment by mgieseki** [comment]
I don't have a Solaris system available, so unfortunately I can't say anything about the TeX Live build of dvisvgm for Solaris at the moment. Maybe @mojca could give some feedback?

**Comment by mgieseki** [comment]
Since I can't help you with this issue, you might also want to ask for information on the [TL mailing list](https://tug.org/mailman/listinfo/tex-live).

**Comment by joachim42** [comment]
Running Solaris 11.4 on a VM probably won't help anyway. I got a VM with an early version of 11.4 myself, and dvisvgm is working fine on it, so I suspect the error occurs only on very recent patchlevels (which AFAIK are not available for VMs). Now trying to compile dvisvgm on one of our "real" Solaris servers.

**Comment by joachim42** [comment]
So far my attempts to compile dvisvgm on Solaris have failed because of kpathsea. There is no precompiled kpathsea library for Solaris (as opposite to Linux), i. e., libkpathsea.so.6 is not available. The TexLive distribution doesn't contain the library either, there are only a few executables which I assume have been statically linked with the kpathsea library, but the library itself is not present. So I'll have to build that one myself too, independent from Tex, but couldn't find any information how to do it. Does anybody know where I should look?

**Comment by mgieseki** [comment]
I guess the easiest way would be to check out the [TeX Live sources](https://www.tug.org/texlive/svn) from the SVN or Git repository and [build](https://www.tug.org/texlive/build.html) the desired components from there. The build process is pretty straight forward although a bit time-consuming, and ensures that you get compatible libraries and executables.

**Comment by mgieseki** [comment]
I can't really tell what's the issue here but I suppose it's related to incompatible changes in the system libraries. Do the Solaris release notes or change logs contain any hints about that? 
Additionally, you could run dvisvgm via [Valgrind](https://valgrind.org) and check if the output contains further helpful information about the origin of the segfault. Since the TL binaries are probably optimized and don't contain debug symbols, it might not be the case, though.

**Comment by mojca** [comment]
I can compile on the same system with debug symbols on if that helps in any way.

**Comment by joachim42** [comment]
Yes please. Would be worth trying.

**Comment by mgieseki** [comment]
@joachim42 have you been able to get the problem sorted? Can we close the issue here?

**Comment by joachim42** [comment]
I still don't have a working precompiled binary, but the one I compiled myself is OK, so I'll use this one if necessary. So yes, closing the issue now.
