### ISSUE TITLE
dvisvgm version for TeX Live 2022

### ISSUE THREAD

**Issue by t-tk** [mgieseki/dvisvgm#172]
What version is appropriate  for TeX Live 2022?
Currently [TeX Live svn repository](https://www.tug.org/svn/texlive/trunk/Build/source/texk/dvisvgm/) includes dvisvgm 2.11.1 .
Latest released version of dvisvgm seems [2.12](https://github.com/mgieseki/dvisvgm/releases/tag/2.12) and more updates are in master branch .
I wonder whether more updated stable version will be released within schedule of TeX Live 2022.
I would appreciate if you make comment on your plan.

TeX Live 2022 development is scheduled as following:

Plan for TeX Live 2022:
15feb: candidate/final sources committed, test builds begin.
25feb: tlpretest starts, CTAN updates continue there and in tlnet.
10mar: code freeze for final build, major bug fixes only.

**Comment by mgieseki** [comment]
I'm currently preparing version 2.13 which will be released in the next few days. It will contain all the latest commits from the master branch.

**Comment by mgieseki** [comment]
dvisvgm 2.13 is now available for download.

**Comment by t-tk** [comment]
Thank you.
