### ISSUE TITLE
pdffile special ignores llx, lly, urx, ury options

### ISSUE THREAD

**Issue by agrahn** [mgieseki/dvisvgm#174]
In the current Git version, the `pdffile` special seems to ignore the `llx`, `lly`, `urx`, `ury` options. This has worked in the 2.11.1 version that ships with TL-21.

Here is an example, `main.tex`, that makes use of both, `PSfile` and `pdffile`, specials.

The embedded images, `example.(ps|pdf)`, show a black square and a frame with 10bp separation. With `llx=10` and `lly=10`, the black square should appear next to the letter "x" and sit on the same baseline. 

`main.tex`; convert with  `dvisvgm --zoom=-1 --bbox=papersize --font-format=woff2 main.dvi`

````latex
\documentclass{article}
\usepackage[a6paper]{geometry}

\begin{document}
\ \\[1in]
x\special{pdffile="example.pdf" llx=10 lly=10 urx=62 ury=62}\\[1in]
x\special{PSfile="example.ps" llx=10 lly=10 urx=62 ury=62}
\end{document}
````

Source of `example.ps` and [`example.pdf`](https://github.com/mgieseki/dvisvgm/files/7921133/example.pdf):
````latex
\documentclass{standalone}
\usepackage{tikz}

\begin{document}
\begin{tikzpicture}
\useasboundingbox (0,0) rectangle (1in,1in);
\draw[very thick] (0,0) rectangle (1in,1in);
\fill (10bp,10bp) rectangle (62bp,62bp);
\end{tikzpicture}
\end{document}
````

**Comment by mgieseki** [comment]
Thanks for reporting this regression. It slipped in with a fix of another bug. I'll push a patch shortly.
