### ISSUE TITLE
rawdef special does not evaluate  {?(...)} expressions

### ISSUE THREAD

**Issue by agrahn** [mgieseki/dvisvgm#175]
The subject says it all. Thank you for consideration. Here is a minimal example:

````tex
test

\special{dvisvgm:rawdef <!-- {?(x-x)} {?(y-y)} -->}
\special{dvisvgm:raw <!-- {?(x-x)} {?(y-y)} -->}

\bye
````

**Comment by mgieseki** [comment]
That's easy to add. Just a moment...

**Comment by agrahn** [comment]
Thanks a lot for fixing both issues so fast! I successfully ran the new version on some of my inputs. Everything works as expected! :smile:

**Comment by mgieseki** [comment]
You're welcome. Great to hear that everything seems to work now. Let me know if you find any further problems with the latest version.
