### ISSUE TITLE
Fix https://dvisvgm.de/Downloads/

### ISSUE THREAD

**Issue by hpreusse** [mgieseki/dvisvgm#180]
The pages says for Ubuntu: "On [Ubuntu](https://www.ubuntu.com/), an old version of dvisvgm is part of package texlive-extra-utils which can be installed with...".

This is not correct any more, in 2019 Debian (and hence Ubuntu) started providing dvisvgm as separate package. Please be so kind to fix the page.

**Comment by mgieseki** [comment]
Thanks for the hint. I'll fix it shortly.
