### ISSUE TITLE
DVI → SVG lost default LaTeX font on MikTeX

### ISSUE THREAD

**Issue by VincentTam** [mgieseki/dvisvgm#186]
Background

I'm using the same version as in https://github.com/mgieseki/dvisvgm/issues/184, and the MWE from https://github.com/MiKTeX/miktex/issues/1112#issuecomment-1159117316

Problem

1. I compiled with `latex`.
2. I used `dvisvgm` without `-P`.
3. The resulting SVG doesn't have LaTeX's default font.

```
$ latex 220617-fill
This is pdfTeX, Version 3.141592653-2.6-1.40.24 (MiKTeX 22.3) (preloaded format=latex.fmt)
 restricted \write18 enabled.
entering extended mode
(220617-fill.tex
LaTeX2e <2022-06-01> pre-release-0 (develop 2022-6-17 branch)
L3 programming layer <2022-06-02>
(C:\Users\sere\AppData\Local\Programs\MiKTeX\tex/latex/standalone\standalone.cl
s
Document Class: standalone 2018/03/26 v1.3a Class to compile TeX sub-files stan
dalone
...
[1] [2] (220617-fill.aux) )
Output written on 220617-fill.dvi (2 pages, 19180 bytes).
Transcript written on 220617-fill.log.

$ dvisvgm -o foobar.svg 220617-fill
pre-processing DVI file (format version 2)
processing page 1
  graphic size: 213.73187pt x 173.012041pt (75.118161mm x 60.806778mm)
  output written to foobar.svg
1 of 2 pages converted in 0.165 seconds
```

![foobar](https://user-images.githubusercontent.com/5748535/174389496-d3bb779d-f957-471f-9713-346c44a1bdef.svg)

Expected output:

A SVG that looks like the following (with transparent background).

![image](https://user-images.githubusercontent.com/5748535/174389731-e82ef257-ca24-4ac5-942b-b715841fc43b.png)

I saw that GhostScript is in the dependencies.  However, with MikTeX, the command for GS is `mgs` instead of `gs`.  Does `dvisvgm` recognise this?

**Comment by mgieseki** [comment]
I guess, the SVG file contains the correct font data but your SVG viewer can't render it properly. That's a common issue. If you call dvisvgm with option [`--no-fonts`](https://dvisvgm.de/Manpage#opt-no-fonts), which replaces all text elements by paths, or [`--font-format=woff`](https://dvisvgm.de/Manpage#opt-font-format), the SVG should render correctly. There's also some information about this in the [FAQ](https://dvisvgm.de/FAQ).

**Comment by VincentTam** [comment]
Thx very much with your response & link to FAQ.  I finally got the exacted output. :tada:

![dvisvgm pgfplots](https://user-images.githubusercontent.com/5748535/174452321-b78ee8d9-371b-43c4-9e4e-f4ed26a864d8.svg)

**Comment by VincentTam** [comment]
For personal reference only.

![foobar](https://user-images.githubusercontent.com/5748535/174452553-cd79f0ba-972d-4286-9288-e6526e065204.svg)

here's the result run with `--no-fonts`.

![image](https://user-images.githubusercontent.com/5748535/174452590-6b8f8ac8-cfe8-4102-9a72-a45cffaecc41.png)

it's OK after uploading through GitHub.

However, the SVG created by `--font-format=woff` that I had uploaded in my prev msg would be distorted after GitHub upload.

![image](https://user-images.githubusercontent.com/5748535/174452762-0a7fee0e-da57-41ba-aa3e-1ec7cf83b612.png)

**Comment by VincentTam** [comment]
what surprises me is that the good svg takes less spaces than the bad one:

```
$ curl -L https://user-images.githubusercontent.com/5748535/174452553-cd79f0ba-972d-4286-9288-e6526e065204.svg > gd.svg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13116  100 13116    0     0   130k      0 --:--:-- --:--:-- --:--:--  132k
$ curl -L https://user-images.githubusercontent.com/5748535/174452321-b78ee8d9-371b-43c4-9e4e-f4ed26a864d8.svg > bd.svg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13362  100 13362    0     0   189k      0 --:--:-- --:--:-- --:--:--  189k
$ ls -l {gd,bd}.svg
-rw-r--r-- 1 sere 197609 13362 juin  18 21:03 bd.svg
-rw-r--r-- 1 sere 197609 13116 juin  18 21:03 gd.svg
```

**Comment by mgieseki** [comment]
Great to hear that you were able to fix the problem.

>However, the SVG created by `--font-format=woff` that I had uploaded in my prev msg would be distorted after GitHub upload.

That's a security measure of the web browser which prevents loading the embedded font data.

> What surprises me is that the good svg takes less spaces than the bad one:

The base64 encodings of the embedded WOFF fonts are quite lengthy and enlarge the file a bit. In contrast, the path variant without any fonts is more compact. You can reduce the file size even more by restricting the number of decimal places used in the SVG, e.g. with `--precision=2` and by using relative path commands (option `--relative`).

**Comment by VincentTam** [comment]
I appreciate your help.  I used `-d 2` and the file size is reduced by 30-40%.

![foobar](https://user-images.githubusercontent.com/5748535/174454795-c09be583-7748-43db-a6a7-1936b16d775a.svg)

```
$ dvisvgm --no-fonts -R -d 2 -o foobar.svg 220617-fill.dvi
pre-processing DVI file (format version 2)
processing page 1
  graphic size: 213.73pt x 173.01pt (75.12mm x 60.81mm)
  output written to foobar.svg
1 of 2 pages converted in 0.119 seconds

$ curl -L https://user-images.githubusercontent.com/5748535/174454795-c09be583-7748-43db-a6a7-1936b16d775a.svg > precision2.svg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8266  100  8266    0     0   115k      0 --:--:-- --:--:-- --:--:--  115k

$ ls -l precision2.svg 
-rw-r--r-- 1 sere 197609 8266 juin  18 21:39 precision2.svg
```
