### ISSUE TITLE
[BUG] Regular polygon problem

### ISSUE THREAD

**Issue by VincentTam** [mgieseki/dvisvgm#189]
# Background
I'm using the same setup as in my previous issues.
# Goal
Draw a regular polygon with *n* vertices marked with a circular dot and a label *Vₖ* with *k* = 1,…,*n*.
# Input
```tex
\documentclass[tikz]{standalone}
\usetikzlibrary{calc}
\begin{document}
\newcommand\myR{2}
\newcommand\n{7}
\newcommand\dTheta{360/\n}
\tikzset{
  every pin edge/.style={opacity=0},
  pin distance=2pt,
  mypt/.style={circle,fill=black,minimum size=0.5pt,inner sep=-2pt},
}
\begin{tikzpicture}
\foreach \k in {1,...,\n} {\coordinate[mypt,pin={\dTheta*\k}:{$V_{\k}$}] (V\k) at ({\dTheta*\k}:\myR);}
\foreach \k in {2,...,\n} {\draw (V\the\numexpr\k-1) -- (V\k);}
\draw (V7) -- (V1);
\end{tikzpicture}
\end{document}
```
Use `latex 220627-reg-n-gon` and `dvisvgm 220627-reg-n-gon` to generate the SVG file.
ℹ️ I removed `--no-fonts` to simplify the above command.
# Actual output
![actual output](https://user-images.githubusercontent.com/5748535/175974526-a84be2c5-6336-4af1-beb0-c20c1929d2b5.png)
# Expected output
![VS code PDF output](https://user-images.githubusercontent.com/5748535/175974736-3d41bd2c-46e2-45b5-afe4-30751b7cc1fe.png)
# Problem
How can I get the expected output?

**Comment by mgieseki** [comment]
The problem is most likely caused by a Ghostscript version that is too old. Your example makes use of transparency settings which require at least GS 9.52. All previous versions don't provide the interface to access the transparency operators from external applications like dvisvgm. If you use the GS library coming with MiKTeX which is based on GS 9.25, then that's the reason. In this case you need to install a newer GS version.
Alternatively, you can specify document class option `dvisvgm` to embed SVG instead of PS specials into the DVI file.

**Comment by VincentTam** [comment]
thanks for reply.  i'm using GS 9.52 the came with MikTeX.
![image](https://user-images.githubusercontent.com/5748535/176004810-2741dc97-e781-4022-b45d-eb6b3b2a8dd0.png)

**Comment by mgieseki** [comment]
> thanks for reply. i'm using GS 9.52 the came with MikTeX. 

Nope, it's 9.25. 😃

**Comment by VincentTam** [comment]
oops nice catch!  thx for your alternative.  it's really helpful.  it seems that there's more config work in the first approach and i really wish to deal with other stuff (like learning TikZ 3D and animation).
![image](https://user-images.githubusercontent.com/5748535/176014407-1bf483b5-1478-45ce-8071-9e972c3a4e64.png)

**Comment by mgieseki** [comment]
Using a different GS version is pretty easy. Just install [Ghostscript 9.55.0](https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/tag/gs9550), for example, and assign the absolute file path of `gsdll64.dll` (if you use the 64-bit MiKTeX) or `gsdll32.dll`  to environment variable `LIBGS`. That's it.

**Comment by VincentTam** [comment]
thx again.
 
![image](https://user-images.githubusercontent.com/5748535/176046534-53aa9935-199d-45d2-a90e-20d973566d74.png)

![image](https://user-images.githubusercontent.com/5748535/176046619-94fde818-9758-4a36-9378-24e3a8136f6c.png)
