### ISSUE TITLE
auto-detection of libgs on recent macOS

### ISSUE THREAD

**Issue by bgvoisin** [mgieseki/dvisvgm#197]
The auto-detection of libgs on macOS has given rise to several issues, now closed, such as [https://github.com/mgieseki/dvisvgm/issues/66](https://github.com/mgieseki/dvisvgm/issues/66), [https://github.com/mgieseki/dvisvgm/issues/143](https://github.com/mgieseki/dvisvgm/issues/143) and [https://github.com/mgieseki/dvisvgm/issues/157](https://github.com/mgieseki/dvisvgm/issues/157).

The following is about a new problem, connected with recent changes in Ghostscript and macOS. This is viewed within the context of MacTeX, the Mac version of TeX Live (I'm part of the team preparing it every year, alongside Dick Koch). MacTeX is designed to require macOS and nothing else; it installs Ghostscript in `/usr/local/{bin,lib,share}/`, with libgs an optional install, and does not set any environment variable. So the following may not apply to MacPorts or Homebrew.

First, with its latest release (21 August 2022), Ghostscript bumped its major version to 10. If I'm interpreting the code in lines 133 ff of Ghostscript.cpp right, 

`	const int abi_min=7, abi_max=9; // supported libgs ABI versions`
`	for (int i=abi_max; i >= abi_min; i--) {`

this means dvisvgm assumes libgs has a major version between  7 to 9 and thus `abi_max` needs to be set to 10.

The second problem is more worrying and, after some debugging, seems linked with code signing, notarization and runtime hardening, which were introduced gradually over the last macOS versions. (I'm not a developer myself, so the following description may be inaccurate or inconsistent; if so, I apologize in advance.)

As a consequence of these, the working of dlopen has changed. Until late last year, as reported for example in

[https://github.com/cl-plus-ssl/cl-plus-ssl/issues/138#issuecomment-971821510](https://github.com/cl-plus-ssl/cl-plus-ssl/issues/138#issuecomment-971821510)

the man page of dlopen contained

`When path does not contain a slash character (i.e. it is just a leaf name),`
`dlopen() searches the following until it finds a compatible Mach-O file:`
`$LD_LIBRARY_PATH, $DYLD_LIBRARY_PATH, current working directory,`
`$DYLD_FALLBACK_LIBRARY_PATH.`

and the man page of dyld said

`      DYLD_FALLBACK_LIBRARY_PATH`
`             This is a colon separated list of directories that contain`
`             libraries.  If a dylib is not found at its install  path, dyld`
`             uses this as a list of directories to search for the dylib.  By`
`             default, it is set to /usr/local/lib:/usr/lib.`

So the search for libgs included `/usr/local/lib/` by default.

Now, on MacOS 13.0 Ventura Beta which I'm using, but I assume the change extends to recent versions of macOS 12 Monterey as well, the man page of dlopen, dated 20 January 2022, says

`     When path does not contain a slash character (i.e. it is just a leaf`
`     name), dlopen() will do searching.  If $DYLD_LIBRARY_PATH was set at`
`     launch, dyld will first look in that directory.  Next, if the calling`
`     mach-o file or the main executable specify an LC_RPATH, then dyld will`
`     look in those directories. Next, if the process is unrestricted, dyld`
`     will search in the current working directory. Lastly, for old binaries,`
`     dyld will try some fallbacks.  If $DYLD_FALLBACK_LIBRARY_PATH was set at`
`     launch, dyld will search in those directories, otherwise, dyld will look`
`     in /usr/local/lib/ (if the process is unrestricted), and then in`
`     /usr/lib/.`

So, in essence, when the process is restricted `/usr/local/lib/` is excluded from dlopen's default search path. No indication is given on what "restricted process" means, and I couldn't find any online. I assume this is connected with runtime hardening, a form of sandboxing.

Namely, when a binary is compiled for packaging and distribution, it must be signed, notarized and hardened. By hardened it is meant that many operations are disabled by default, and if one is required it must be added as an entitlement (an exception), the possible entitlements being listed at

[https://developer.apple.com/documentation/xcode/configuring-the-hardened-runtime](https://developer.apple.com/documentation/xcode/configuring-the-hardened-runtime)

The dvisvgm binary in MacTeX is signed, notarized and hardened, with a "Disable Library Validation" entitlement. Apparently, that's not enough.

Namely, MacTeX installs (considering gs 9.56.1)

`/usr/local/lib/libgs.9.56.dylib`
`/usr/local/lib/libgs.9.dylib`
`/usr/local/lib/libgs.dylib`

all symlinks to `libgs.dylib.9.56` inside `/usr/local/share/ghostscript/9.56.1/lib/`. Compiling libgs instead from source, you get

`/usr/local/lib/libgs.dylib.9`
`/usr/local/lib/libgs.dylib`
`/usr/local/lib/libgs.dylib.9.56`

the first two symlinks to the third. Both libgs installs have a naming structure and location expected by dvisvgm.

Indeed, if I compile dvisvgm locally, so that it runs unrestricted on my machine, libgs is seen and can be used:

`% dvisvgm -l`
`bgcolor    background color special`
`color      complete support of color specials`
`dvisvgm    special set for embedding raw SVG snippets`
`em         line drawing statements of the emTeX special set`
`html       hyperref specials`
`papersize  special to set the page size`
`pdf        PDF hyperlink, font map, and pagesize specials`
`ps         dvips PostScript specials`
`tpic       TPIC specials`

`% dvisvgm -V1`
`dvisvgm 2.13.3`
`--------------`
`brotli:      1.0.9`
`clipper:     6.2.1`
`fontforge:   20160721`
`freetype:    2.11.1`
`Ghostscript: 9.56.1`
`kpathsea:    6.3.4`
`potrace:     1.16`
`xxhash:      0.8.1`
`zlib:        1.2.11`

If I repeat the same with dvisvgm from MacTeX, the output is the same but without the ps line for `dvisvgm -l` and without the Ghostscript line for `dvisvgm -V1`, so libgs is not seen. This implies that the "Disable Library Validation" entitlement is not enough, or not the proper entitlement, to allow dlopen to look into `/usr/local/lib/`.

If `LIBGS` is set or `--libgs` is used, the matter is solved and dvisvgm uses libgs. But that's not auto-detection.

That's as far as I went. Maybe "Allow DYLD Environment Variables" is the entitlement to consider instead, or maybe `DYLD_FALLBACK_LIBRARY_PATH` needs to be reset to its original (unrestricted) default `/usr/local/bin:/usr/bin` in combination with this entitlement.

The problem is that I haven't a (paying) Apple Developer ID to experiment with code signing, notarization and runtime hardening myself. And, not being an actual developer, I probably wouldn't go far anyway.

So the above is just to raise attention to the matter, with the hope that, should the problem be experienced by somebody else later, this would provide a starting point and a developer with the required skills and Apple ID would pick up from there and solve the matter.

**Comment by bgvoisin** [comment]
Indeed, after further investigation (and the purchase of a Developer ID so that I could test code signing), it turns out setting `DYLD_FALLBACK_LIBRARY_PATH` or `DYLD_LIBRARY_PATH` in the dvisvgm source is of no help whatsoever. The only way forward for a hardened runtime is to call `dlopen` with the full path to the library.

This is in agreement with the current version of the `dlopen` man page, which says (macOS since 20 January 2022), at the beginning of its Searching section,

```
     In general, dyld does not search for dylibs.  Dylibs are specified via a
     full path, either as a static dependent dylib in a mach-o file, or as a
     path passed to dlopen() , But during development the env vars
     DYLD_LIBRARY_PATH and DYLD_FRAMEWORK_PATH can be used to override the
     specified path and look for the leaf framework/dylib name in the
     specified directories.
```

This is confirmed by the answer [https://stackoverflow.com/a/73931251](https://stackoverflow.com/a/73931251) to a similar question two weeks ago. This answer is by the author of XQuartz (aka X11 for the Mac), hence somebody with quite some experience on the matter.

Based on this, Dick Koch (the MacTeX architect and builder) suggested to call `dlopen` again, once it has been called with argument `libgs.dylib` and failed, this time with the full path `/usr/local/lib/libgs.dylib` at which the library is installed by MacTeX. This would mean adding a few lines of code between lines 149 and 150 of `Ghostscript.cpp`, so that

```
#if defined(__APPLE__)
		dlname = "libgs." + to_string(i) + ".dylib";
		if (loader.loadLibrary(dlname))
			return dlname;
		dlname = "libgs.dylib." + to_string(i);
		if (loader.loadLibrary(dlname))
			return dlname;
#endif
```

becomes

```
#if defined(__APPLE__)
		dlname = "libgs." + to_string(i) + ".dylib";
		if (loader.loadLibrary(dlname))
			return dlname;
		dlname = "libgs.dylib." + to_string(i);
		if (loader.loadLibrary(dlname))
			return dlname;
	// dlopen() requires an absolute path in a hardened runtime such as installed by MacTeX
		dlname = "/usr/local/lib/libgs." + to_string(i) + ".dylib";
		if (loader.loadLibrary(dlname))
			return dlname;
		dlname = "/usr/local/lib/libgs.dylib." + to_string(i);
		if (loader.loadLibrary(dlname))
			return dlname;
#endif
```

Having done that, then compiled and signed the binary with the runtime option, I get

```
% dvisvgm -V1
dvisvgm 2.13.3
--------------
brotli:      1.0.9
clipper:     6.2.1
fontforge:   20160721
freetype:    2.11.1
Ghostscript: 10.0.0
kpathsea:    6.3.4
potrace:     1.16
xxhash:      0.8.1
zlib:        1.2.11
```

as expected. (The version is 2.13.3 because I worked with the TeX Live 2022 sources from last spring.)

**Comment by mgieseki** [comment]
Great, thanks for the additional information. I've slightly adapted your proposed changes and am going to commit them shortly.
