### ISSUE TITLE
ghostscript-10.0 undefined reference to `gs_error_names'

### ISSUE THREAD

**Issue by zarniwhoop73** [mgieseki/dvisvgm#199]
With ghostscript-10.0 gs_error_names is no longer available. A quick and dirty fix is in use at (beyond) linuxfromscratch
`sed "s/gs_error_names\[/error_names[/" -i src/Ghostscript.cpp` 

That is also needed on (prerelease) dvisvgm-3.0.

**Comment by mgieseki** [comment]
The issue has already been fixed. See #195.
