### ISSUE TITLE
Cannot build v3.0 with ghostscript 10

### ISSUE THREAD

**Issue by stertooy** [mgieseki/dvisvgm#206]
This seems to be the same issue as #195. This was fixed in https://github.com/mgieseki/dvisvgm/commit/9bf81fd0b6e7876e5079e917ed7e12163b9e7f7f, but the fixes seem to have been undone in https://github.com/mgieseki/dvisvgm/commit/c6d578aea100b28625737942c37ce1269e976dba.

**Comment by mgieseki** [comment]
Yes, that's a silly regression. I'll revert the GS-related changes made by c6d578aea100b28625737942c37ce1269e976dba.
