### ISSUE TITLE
Update the year to 2023 in copyright statements

### ISSUE THREAD

**Issue by YDX-2147483647** [mgieseki/dvisvgm#213]
It's 2023 now. (Happy new year!)

Relevant commits: [2022](https://github.com/mgieseki/dvisvgm/commit/13c6e039e4dfece0beb6887ba80ee9e3eadd03d1), [2021](https://github.com/mgieseki/dvisvgm/commit/b4c1834ce794bd8f9a11ff764464dff573caa097), [2020](https://github.com/mgieseki/dvisvgm/commit/e472bbf7a10705245017423619f9f4ed7f423c27).

---

I've made an issue rather than a PR: There're a number of files to change (⇒ maybe hard to review), and not all statements should be updated (as below).

https://github.com/mgieseki/dvisvgm/blob/d2a6a8a576ec053ca3d4453ad0489807ed9871c8/tests/gtest/include/gtest/internal/custom/gtest-port.h#L1-L2

**Comment by mgieseki** [comment]
Happy new year to you too! 
I'm somewhat at a loss at the moment. There's already a [commit](https://github.com/mgieseki/dvisvgm/commit/c8a6c4f0dca7390494d8b647bb630d16302be97e) that updates the year to 2023. Did I miss something there?

**Comment by YDX-2147483647** [comment]
Sorry, it's my problem… According to my browser's history, I was on v3.0 pre-release then.
