### ISSUE TITLE
3.0.1 sources in https://github.com/TeX-Live/texlive-source

### ISSUE THREAD

**Issue by agrahn** [mgieseki/dvisvgm#219]
Martin,  would you please upload the dvisvgm 3.0.1 sources to the texlive-source Git repo? Otherwise, it is close to impossible to compile and test the new release in a current texlive environment. Thanks!

**Comment by mgieseki** [comment]
I've prepared a first patch to update the TL sources:
https://github.com/mgieseki/texlive-source/tree/dvisvgm-3
It's not yet tested properly but builds on my Linux machine. Maybe you'd like to test it before I create a PR in the TL repo.

**Comment by agrahn** [comment]
> [TeX-Live/texlive-source#59](https://github.com/TeX-Live/texlive-source/pull/59)

Thank you! Hopefully, Karl will merge this soon.

**Comment by agrahn** [comment]
I think we can close this now as the `dvisvgm` sources are up to date in the TeXLive svn repo. What do you think?

**Comment by mgieseki** [comment]
Yes, I agree. As far as I can tell, there's nothing further to be done from my side at the moment.
