### ISSUE TITLE
Converting PDFs (without background) to svg with mutool

### ISSUE THREAD

**Issue by povpie** [mgieseki/dvisvgm#220]
On my workflow I need to remove the background from the pdf before converting it to svg(with mutool).

**Issue**: on some PDFs the removal of the background makes the conversion become very messed when there is a curved text on the pdf. The problem don't seem to show up on straight text.

PDF with background:
![image](https://user-images.githubusercontent.com/91896759/213275038-c36aa674-dfd0-4700-805e-55327537b383.png)

PDF to SVG (with background)
![image](https://user-images.githubusercontent.com/91896759/213275568-3b44de9c-b665-4d84-ae1b-1fd6b70a9187.png)

PDF with no background:
![image](https://user-images.githubusercontent.com/91896759/213275818-f8f4c0bf-f3f9-460c-aec1-46198becd711.png)

PDF to SVG (no background)
![image](https://user-images.githubusercontent.com/91896759/213277600-b93b1728-1151-4009-83a3-b9dc2f019e50.png)

I attach below the pdf with background and the one without.
(with background)
[complex3.pdf](https://github.com/mgieseki/dvisvgm/files/10449994/complex3.pdf)

(without background)
[complex3noBG.pdf](https://github.com/mgieseki/dvisvgm/files/10450009/complex3noBG.pdf)

**Comment by mgieseki** [comment]
Thanks for reporting the issue. It's a bug in dvisvgm's new PDF handler. I've fixed it and am going to commit the patch shortly.
