### ISSUE TITLE
Viewbox min-y attribute has non-zero value

### ISSUE THREAD

**Issue by povpie** [mgieseki/dvisvgm#223]
Problem:10px are being added to the height of the svg 

Here is a simple example (the problem is happening in all my conversions **pdf to svg**). The problem seems to arise because of the `viewbox` attribute for `min-y` is not zero (in the screenshot below it has value of =7.920007pt, but should be zero)
command I'm using:` dvisvgm --pdf -Oall -fwoff2`

Additional question:
(2) Is there an options to have the resulting svg with **px** dimensions instead of **pt**? I use the svg for display and not for printing.
(3) I noted that the `height` attribute and the `viewbox(height)` usually gets converted to a strange approximation of the rounded/correct number. In the exemple below it get the value of `809.999993pt` instead of `810pt`, but the width is the correct 810pt

![image](https://user-images.githubusercontent.com/91896759/214200609-61219579-d875-4938-be47-af93704eac34.png)

(svg with an overflown shape at the bottom but the same non-zero `min-y` problem)

![canvapdfjustbg1](https://user-images.githubusercontent.com/91896759/214202839-7d573eac-6420-44d6-86d9-b753b87c9f60.svg)

**Comment by mgieseki** [comment]
> Problem:10px are being added to the height of the svg

Please upload a simple PDF file I can use to reproduce the problem.


> Is there an options to have the resulting svg with **px** dimensions instead of **pt**? 

No, but you can use option `--zoom=-1` to remove the `width` and `height` attributes which results in an SVG that automatically adapts its size to the available space. 


> I noted that the `height` attribute and the `viewbox(height)` usually gets converted to a strange approximation of the rounded/correct number. In the exemple below it get the value of `809.999993pt` instead of `810pt`, but the width is the correct 810pt

Just use option `--precision` to reduce the number of decimal places, e.g. `--precision=2` (or shorter: `-d2`).

**Comment by povpie** [comment]
[justbgcolor.pdf](https://github.com/mgieseki/dvisvgm/files/10489484/justbgcolor.pdf)

**Comment by mgieseki** [comment]
The computation of the PDF mediabox was buggy. I've fixed it with the upcoming patch.
