### ISSUE TITLE
pdf to svg (text becomes empty)

### ISSUE THREAD

**Issue by povpie** [mgieseki/dvisvgm#224]
I used another software to create a few pdfs but when converting to svg (`dvisvgm --pdf -Oall -fwoff2,ah`) I'm getting an empty svg where texts are supposed to be. 

[flyerExample3.pdf](https://github.com/mgieseki/dvisvgm/files/10493980/flyerExample3.pdf)

It seems that the fonts don't even get recognized because I don't receive warning error from the missing autohint.

**Comment by mgieseki** [comment]
This is a tricky issue because the CID font data embedded in the PDF file is incomplete so that the current PDF handler can't match the font names. I've added a workaround that hopefully works with most PDF files of this type.
