### ISSUE TITLE
Misrender of "periodic table" example using dvisvgm backend driver

### ISSUE THREAD

**Issue by rfdonnelly** [mgieseki/dvisvgm#227]
Hello.  This is a follow on to #225 which was resolved by having me use the PGF/TikZ dvisvgm backend driver.  Thank you for that.  Using the dvisvgm backend driver fixed the "focused ion beam system" example but it breaks the period table example at https://tikz.net/periodic-table.

The labels for the gray elements get misplaced (red annotations mine):

![image](https://user-images.githubusercontent.com/28975/216795518-92ffab39-df8b-4aaa-8b21-967545ae96b5.png)

I suspect this is an issue with the PGF/TikZ dvisvgm backend driver instead of dvisvgm itself but I thought I would start here first to confirm.

## Screenshot Comparison

Click the images for the corresponding SVG/PDF source file:

<table>
<tr>
<th>SVG using default driver
<th>SVG using dvisvgm driver
<th>PDF
<tr>
<th><a href="https://user-images.githubusercontent.com/28975/216795640-b3764908-8cd1-406c-b745-fea819155ea6.svg"><img src="https://user-images.githubusercontent.com/28975/216795615-87a18c24-4c52-4dfe-9821-d29f98ae0d2e.png"></a>
<th><a href="https://user-images.githubusercontent.com/28975/216795651-acc474c4-beab-443b-b89d-0a810e6ce696.svg"><img src="https://user-images.githubusercontent.com/28975/216795624-91926897-b8be-4823-876f-1d175d606fa7.png"></a>
<th><a href="https://github.com/mgieseki/dvisvgm/files/10609970/default.pdf"><img src="https://user-images.githubusercontent.com/28975/216795630-f358d2f7-e4f1-43ff-bb4b-f13b2dd47a8f.png"></a>
</table>

## Versions

I get the same results with both of the following configurations.

### Alpine Linux 3.17

* pgfversion: 3.1.9a
* pdfTeX 3.141592653-2.6-1.40.24 (TeX Live 2022/Alpine Linux)
* dvisvgm 3.0.2

### texlive Docker Image

* pgfversion: 3.1.10
* pdfTeX 3.141592653-2.6-1.40.24 (TeX Live 2022)
* dvisvgm 2.13.3

## Reproduce

Copy the example from https://tikz.net/periodic-table to `default.tex`.

Copy `default.tex` to `dvisvgm.tex` and modify as follows:

```diff
--- examples/periodic-table/default.tex	2023-02-04 15:02:12.868609073 -0800
+++ examples/periodic-table/dvisvgm.tex	2023-02-04 15:02:12.918592361 -0800
@@ -1,9 +1,9 @@
 % Adapted from https://texample.net/tikz/examples/periodic-table-of-chemical-elements.
 % All Credit to Ivan Griffin.
 
-\documentclass[tikz,border=5mm]{standalone}
+\documentclass[dvisvgm,tikz,border=5mm]{standalone}
 \usetikzlibrary{shapes,calc}
 
 \begin{document}
 
 \newcommand{\ElemLabel}[4]{
```

Then run:

```sh
latex default.tex
dvisvgm --font-format=woff default.dvi

latex dvisvgm.tex
dvisvgm --font-format=woff dvisvgm.dvi
```

**Comment by muzimuzhi** [comment]
A simplified example:
```tex
\ifnum\pdfoutput>0 % pdf output
  \documentclass[tikz, margin=5pt]{standalone}
\else % dvi output
  \documentclass[dvisvgm, tikz, margin=5pt]{standalone}
\fi

\begin{document}
\begin{tikzpicture}
  \node[draw] {before {\color{gray}GRAY} after};
\end{tikzpicture}
\end{document}
```
- Expected (`pdflatex` output):
![image](https://user-images.githubusercontent.com/6376638/216799615-f8348931-9247-42aa-be6f-920c824d32c2.png)
- Actual (`latex -> dvisvgm` output):
![image](https://user-images.githubusercontent.com/6376638/216799655-f7292d5d-5c75-4ff5-bc81-af333689c668.png)

**Comment by muzimuzhi** [comment]
Just a workaround: Since this picture is simple (from ps-special's view), dvisvgm is able to process the .dvi output of `latex` without setting tikz backend to `dvisvgm`.

Hence the original `\documentclass[tikz,border=5mm]{standalone}` works.

**Comment by rfdonnelly** [comment]
Thank you for minimizing the example!

**Comment by mgieseki** [comment]
Thanks for reporting the issue. It's a bug in dvisvgm's character handler that's easy to fix. I'll push the patch shortly.

**Comment by muzimuzhi** [comment]
Wow, this once again pushes me to try compiling dvisvgm on macOS, instead of waiting for the update from texlive once a year.

**Comment by rfdonnelly** [comment]
Thank you @mgieseki!
