### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [mgieseki/dvisvgm#230]
Would you like to [wrap any pointer data members](https://github.com/mgieseki/dvisvgm/blob/0839c7fcff2719d85252478cc7b0fbfa0305a92b/src/InputBuffer.cpp#L28 "Update candidate: StreamInputBuffer class") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

**Comment by mgieseki** [comment]
Yes, that's pretty old code. I'll replace the explicitly allocated arrays with vectors so that pointers are no longer needed there.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/mgieseki/dvisvgm/commit/41602d00766eaaad5981d644cbb20278466b1fff "replaced dynamically allocated C arrays with vectors").
