### ISSUE TITLE
Incorrect position of Chinese with XeLaTeX in TexLive

### ISSUE THREAD

**Issue by rehnertz** [mgieseki/dvisvgm#235]
With the following LaTeX code

```tex
\documentclass[preview]{standalone}
\usepackage[UTF8]{ctex}
\begin{document}
    \begin{center}
        Hello 你好 \LaTeX
    \end{center}
\end{document}
```

The output pdf of xelatex is correct:

![pdf-output](https://user-images.githubusercontent.com/22890511/229189755-21b933fa-3a72-4b18-aa2d-7aa3e4adafb7.png)

However, when transforming xdv to svg, i.e.

```
xelatex -no-pdf main.tex
dvisvgm -n main.xdv
```

the Chinese characters are shifted:

![svg-output](https://user-images.githubusercontent.com/22890511/229190187-f89d951a-9f0a-4529-9064-26f79a57f229.png)

TexLive2023 on Windodws 11.

> I'm using manim to build Maths videos, and I need to write Chinese with inline fomulae. I find out that manim uses `dvisvgm -n XXXX.xdv` to generate svg's for videos. It does not support outputs without the option `-n`. Whether or not manim uses other methods to solve this problem, I think this is still a bug in dvisvgm

**Comment by muzimuzhi** [comment]
Just a workaround, if I feed pdf to `dvisvgm` then the baseline in svg is fine.
```
xelatex main.tex
dvisvgm --pdf -n main.pdf
```

**Comment by muzimuzhi** [comment]
It seems the mis-alignment only occurs with CJK fonts and the content in CJK fonts is vertically centered on some axis (perhaps the normal baseline), character by character.
```tex
% !TeX TS-program = xelatex
\documentclass{standalone}
\usepackage{fontspec}

\font\1="FandolHei"
\font\2="Latin Modern Mono"

\begin{document}
  \parbox{\linewidth}{
    Hello {\fontspec{FandolHei}FandolHei} World {\1FandolHei} \\
    Hello {\fontspec{Latin Modern Mono}LM Mono} World {\2LM Mono}
  }
\end{document}
```
PDF
![image](https://user-images.githubusercontent.com/6376638/229199450-e37b3e5c-20ee-4328-ab84-0e423e338963.png)
SVG (generated from `.xdv` with `-n` option)
![image](https://user-images.githubusercontent.com/6376638/229199489-d1dd240b-dd75-4675-ba01-cb647abf294f.png)

**Comment by mgieseki** [comment]
Thanks for reporting the issue and thanks @muzimuzhi for posting the workaround. I've committed a quick fix that will hopefully work in most cases.
