### ISSUE TITLE
the depth info is missing when using latex package hyperref

### ISSUE THREAD

**Issue by c-ding-math** [mgieseki/dvisvgm#246]
I have a tex file test.tex like this:
~~~
\usepackage[active,tightpage]{preview}
\begin{document}
\begin{preview}
$A$
\end{preview}
\end{document}
~~~
If I use 
~~~
latexmk -output-format=dvi test.tex
dvisvgm test.dvi
~~~
then I get the everything as expected in the stdout:
~~~~
...
width = ..., height=..., depth=...
...
~~~~
But when I add the latex package `hyperref` in the tex file
~~~
\usepackage[active,tightpage]{preview}
\usepackage{hyperref}
\begin{document}
\begin{preview}
$A$
\end{preview}
\end{document}
~~~
then the width, height and depth info won't show.

**Comment by mgieseki** [comment]
At the moment, dvisvgm only supports the `hypertex` mode of the `hyperref` package. The PS mode can interfere with the processing of the preview data. The following variant should work:
```tex
\usepackage[hypertex]{hyperref}
```

**Comment by mgieseki** [comment]
I've improved the evaluation of the preview extents so that they are now also recognized if additional PS code interferes with the data.
