### ISSUE TITLE
Missing text from PDF >> SVG

### ISSUE THREAD

**Issue by povpie** [mgieseki/dvisvgm#252]
Version:3.12
Configuration: dvisvgm --pdf -Oall -fwoff2
Problem: missing some text on svg. 

File:
[test1.pdf](https://github.com/mgieseki/dvisvgm/files/13171265/test1.pdf)
<br>
<img src="https://github.com/mgieseki/dvisvgm/assets/91896759/48b89aad-bdba-4904-b159-162e9de79268" width="250" height="auto">
<br>
(additional files)
<br>
[test2.pdf](https://github.com/mgieseki/dvisvgm/files/13171315/test2.pdf)
[test3.pdf](https://github.com/mgieseki/dvisvgm/files/13171318/test3.pdf)

**Comment by mgieseki** [comment]
I can't reproduce the problem. What version of dvisvgm and mutool do you use?

**Comment by povpie** [comment]
dvisvgm 3.1.2 (x86_64-pc-win64)
-------------------------------
brotli:      1.1.0
clipper:     6.2.1
freetype:    2.13.2
Ghostscript: 9.25
MiKTeX:      22.12
mutool:      1.21.0
potrace:     1.16
xxhash:      0.8.2
zlib:        1.3

**Comment by mgieseki** [comment]
Ok, thanks for the additional info. I was able to reproduce the issue now. Unfortunately, it's related to the limited functionality available via `mutool`. The PDF file contains four different font resources that all have the same internal name `PCPYGD+-`:
```
Fonts (4):
        1       (7 0 R):        Type0 'PCPYGD+-' Identity-H (11 0 R)
        1       (7 0 R):        Type0 'PCPYGD+-' Identity-H (12 0 R)
        1       (7 0 R):        Type1 'PCPYGD+-' WinAnsiEncoding (8 0 R)
        1       (7 0 R):        Type1 'PCPYGD+-' WinAnsiEncoding (13 0 R)
```
Therefore, it's not possible to identify the different fonts by their name which is essential for dvisvgm to work properly. Maybe you can tweak the font embedding options of the application used to create the PDF files in order to get more distinct names when subsetting fonts.

**Comment by povpie** [comment]
I'll try to change it manuall. Is is that mutool doesn't identify the ID following the name font? 

![Screenshot (2)](https://github.com/mgieseki/dvisvgm/assets/91896759/d8e1a299-bdc4-495a-9bb3-1d5918461c49)

**Comment by mgieseki** [comment]
> Is is that mutool doesn't identify the ID following the name font?

In the PDF file, there are no numbers appended to the font names. They are probably added by your font downloader. As shown above, all four font objects got the name `PCPYGD+-`. Internally they can be distinguished by their object IDs but mutool doesn't provide a way to make them accessible to the user in the backend. Fonts are referenced there only by their names which might be ambiguous, like in your case.

**Comment by povpie** [comment]
Ah, i see. If I find a solution I'll post it here. Unfortunately there's no option to export the design in different way for fonts on Adobe Express.
