### ISSUE TITLE
Ghostscript 10.01.0+ support

### ISSUE THREAD

**Issue by ryandesign** [mgieseki/dvisvgm#254]
With dvisvgm 3.1.2, when ghostscript 10.02.0 is installed, `dvisvgm --pdf somefile.pdf` produces this error:

```
ERROR: To process PDF files, either Ghostscript < 10.01.0 or mutool is required.
The installed Ghostscript version 10.02.0 isn't supported.
```

This was originally [reported to MacPorts](https://trac.macports.org/ticket/68646) by @OverflowCat.

**Comment by muzimuzhi** [comment]
Starting with 10.01.0, Ghostscript removed its (long-existing PostScript-based) pdf interpreter, hence `dvisvgm` had to choose another tool, mutool.

See `dvisvgm` [v3.0 release notes](https://github.com/mgieseki/dvisvgm/releases/tag/3.0) and its manpage (https://dvisvgm.de/Manpage/).

**Comment by ryandesign** [comment]
So it is not possible for dvisvgm to be rewritten to use Ghostscript 10.01.0+'s new PDF interpreter? Or do you mean Ghostscript 10.01.0+ no longer offers any PDF interpreter?

**Comment by mgieseki** [comment]
Ghostscript replaced its PostScript-based PDF interpreter with a completely new one written in C. Unfortunately, it doesn't provide means to override the PDF operators which was possible before. Thus, dvisvgm no longer can't properly interact with the PDF interpreter. I currently don't see a way to utilize the new Ghostscript releases for dvisvgm's PDF conversion functionality.

**Comment by ryandesign** [comment]
Ok thanks for the explanation. It's a shame that Ghostscript removed a feature you were relying on.

**Comment by muzimuzhi** [comment]
See also #226.

**Comment by mgieseki** [comment]
Just a short addition: Ghostscript is still required for dvisvgm's PostScript functionality, i.e. processing of PS specials or the conversion of PS/EPS files. So, mutool doesn't replace Ghostscript completely. It's only required for handling PDF stuff.
