### ISSUE TITLE
PDF -> SVG: Pixels cut-off on right border

### ISSUE THREAD

**Issue by MagielBruntink** [mgieseki/dvisvgm#256]
In the generated [test.svg](https://github.com/mgieseki/dvisvgm/assets/3635696/82138596-449c-484f-9df8-b7002fff7860) from the attached [test.pdf](https://github.com/mgieseki/dvisvgm/files/13625917/test.pdf), the closing parenthesis `)` has a few pixels cut-off.

<img width="394" alt="image" src="https://github.com/mgieseki/dvisvgm/assets/3635696/771a94a3-7378-41c0-a28a-020119eec0b1">

Command used:
```
dvisvgm.exe --pdf -o test.svg --exact-bbox --no-fonts test.pdf
```

Version of the program (compiled on MSYS2/ucrt):
```
dvisvgm 3.1.2 (x86_64-w64-mingw32)
----------------------------------
brotli:      1.1.0
clipper:     6.2.1
freetype:    2.13.2
Ghostscript: 10.02.1
kpathsea:    6.3.5
mutool:      1.23.7
potrace:     1.16
xxhash:      0.8.2
zlib:        1.3
```

What could be the source of this issue?

**Comment by MagielBruntink** [comment]
The same happens without --exact-bbox

**Comment by mgieseki** [comment]
This seems to be a rounding issue regarding font sizes. I have a look at it later today.
`--exact-bbox` only works with DVI files. EPS and PDF files contain bounding box information which are directly applied to the generated SVG files as well.

**Comment by MagielBruntink** [comment]
Thanks for the fix!

**Comment by mgieseki** [comment]
You're welcome.
