### ISSUE TITLE
TL build patch: main src/Makefile.am

### ISSUE THREAD

**Issue by kberry** [mgieseki/dvisvgm#260]
For the main Makefile.am, here is a further patch for the TL build, for src/Makefile.am.  It basically splits up AM_CXXFLAGS into common and TL/non-TL parts. Also some TL-specific stuff at the end. Again, I hope this does not affect non-TL builds.

I guess I'll attach it since it's longer.
[srcmfam.txt](https://github.com/mgieseki/dvisvgm/files/13954501/srcmfam.txt)

Let me know if problems ... --thanks, karl.

**Comment by mgieseki** [comment]
I needed to adapt the changes a bit in order to prevent non-TL build errors. I hope the patch still works with TL.
[dvisvgm-tl.patch](https://github.com/mgieseki/dvisvgm/files/13964698/dvisvgm-tl.patch)
