### ISSUE TITLE
> and ' gets replaced with " in SVG

### ISSUE THREAD

**Issue by gromnitsky** [mgieseki/dvisvgm#276]
[In this pdf][], which I converted to [an .svg][] with

[In this pdf]: https://sigwait.org/~alex/junk/dvisvgm/1.pdf
[an .svg]: https://sigwait.org/~alex/junk/dvisvgm/1.svg

    $ dvisvgm -s -P -f woff2 1.pdf > 1.svg

some chars (`>` and `'`) got replaced with `"`. This doesn't happen with --no-fonts option.

<img src='https://sigwait.org/~alex/junk/dvisvgm/Google-chrome.0x3c000a6.png'>

~~~
$ dvisvgm -V1
dvisvgm 3.4.1 (x86_64-pc-linux-gnu)
-----------------------------------
brotli:      1.1.0
clipper:     6.2.1
freetype:    2.13.2
Ghostscript: 10.02.1
kpathsea:    6.3.5
mutool:      1.24.6
potrace:     1.16
ttfautohint: 1.8.4
xxhash:      0.8.2
zlib:        1.3.1.zlib-ng
~~~

**Comment by mgieseki** [comment]
Could you please provide a reduced PDF file with only a single line of text showing the issue? The current file is way to big for debugging purposes.

**Comment by gromnitsky** [comment]
[Certainly](https://sigwait.org/~alex/junk/dvisvgm/2.pdf), although now "-f woff2" rendering in Chrome became even more bizarre: `<` got replaced with `>` and the whole line didn't fit into [the svg](https://sigwait.org/~alex/junk/dvisvgm/2.svg):

<img src='https://sigwait.org/~alex/junk/dvisvgm/2.google-chrome.png'>

**Comment by mgieseki** [comment]
Thanks for the shortened file. I've fixed the initial character bug. The clipped text seems to be a different issue. Feel free to open a separate ticket for that one.
