### ISSUE TITLE
MiKTeX.Session could not be initialized error in a normal miktex

### ISSUE THREAD

**Issue by u-fischer** [mgieseki/dvisvgm#41]
I downloaded today dvisvgm-1.8-win32.zip and unpacked it in a folder. When I tried 
dvisvgm --help I get the error message "MiKTeX.Session could not be initialized".

I don't have a portable miktex.

It is a 32-bit miktex, installed as a single user installation in a normal user account (without admin rights)  in D:\miktex2.9. on a 64bit windows 7.

**Comment by u-fischer** [comment]
After a year I made another effort to get it working and found with the help of Christian Schenk a way to register the COM-interface in a single user installation (https://sourceforge.net/p/miktex/bugs/2376/):

1. Open a command line with admin rights (search in den windows search field for cmd.exe, right click and choose "run as administrator").

2. Navigate to the folder of the miktex binaries.

3. Run

~~~~~
regsvr32 MiKTeX209-core-PS.dll
regsvr32 MiKTeX209-core.dll
regsvr32 MiKTeX209-packagemanager-PS.dll
regsvr32 MiKTeX209-packagemanager.dll
~~~~~

**Comment by mgieseki** [comment]
Thank you for your further investigations and the feedback about the solution that fixes the issue. I'll add these information to the FAQ page of the dvisvgm website.

**Comment by RemDelaporteMathurin** [comment]
> 3\. Run
> 
> ```
> regsvr32 MiKTeX209-core-PS.dll
> regsvr32 MiKTeX209-core.dll
> regsvr32 MiKTeX209-packagemanager-PS.dll
> regsvr32 MiKTeX209-packagemanager.dll
> ```

Note: these commands may need to be adapted depending on the MiKTeX version.
At the time of writing:
```
regsvr32 MiKTeX220300-core-PS.dll
regsvr32 MiKTeX220300-core.dll
regsvr32 MiKTeX220300-packagemanager-PS.dll
regsvr32 MiKTeX220300-packagemanager.dll
```

**Comment by deining** [comment]
Three years later, there is again some adaption needed.
With a local MikTeX Installation, that worked for me at the time of writing:

```
cd %LOCALAPPDATA%\Programs\MiKTeX\miktex\bin\x64
regsvr32 MiKTeX240400-core-PS.dll
regsvr32 MiKTeX240400-core.dll
regsvr32 MiKTeX240400-packagemanager.dll
regsvr32 MiKTeX240400-packagemanager-PS.dll
```
