### ISSUE TITLE
DVI error: DVI format 6 not supported

### ISSUE THREAD

**Issue by matthewjhe** [mgieseki/dvisvgm#47]
```bash
$ xelatex -v
XeTeX 3.14159265-2.6-0.99992 (TeX Live 2015)
kpathsea version 6.2.1
Copyright 2015 SIL International, Jonathan Kew and Khaled Hosny.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the XeTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the XeTeX source.
Primary author of XeTeX: Jonathan Kew.
Compiled with ICU version 55.1; using 55.1
Compiled with zlib version 1.2.8; using 1.2.8
Compiled with FreeType2 version 2.5.5; using 2.5.5
Compiled with Graphite2 version 1.2.4; using 1.2.4
Compiled with HarfBuzz version 0.9.40; using 0.9.40
Compiled with libpng version 1.6.17; using 1.6.17
Compiled with poppler version 0.32.0
Compiled with fontconfig version 2.11.93; using 2.11.0
```
Any plan to support dvi format 6?

**Comment by bk322** [comment]
+1

**Comment by mgieseki** [comment]
Sorry for the late reply. I didn't receive a notice from GitHub about this ticket...
I'll look into the specification of the new format to get an overview of the changes. If they didn't add too many new concepts, I can probably add support for format 6 to the next release (which isn't planned yet).

**Comment by bk322** [comment]
DVI v6 doesn't seem to be documented anywhere. Here's my original issue: http://tex.stackexchange.com/questions/254864/set-dvi-version-output-in-xelatex

**Comment by mgieseki** [comment]
Yes, there's no documentation about format 5 either. I had to look into the sources of XeTeX and dvipdfmx to get some information. Maybe that works for format 6 as well. It can take some time, though.

**Comment by mgieseki** [comment]
Fortunately, there are only minor changes to the XDV format that were easy to implement. I've pushed a patch to the code repo that adds support for format 6 to dvisvgm.

**Comment by bk322** [comment]
Great, I just tested it -- it works. When do you think it will be available in CTAN? (so one can use tlmgr to update it)

**Comment by mgieseki** [comment]
As far as I know, the TeX Live maintainers don't provide intermediate updates for the binaries. So you probably have to wait until TeX Live 2016, but I'm not sure. Maybe someone on the TeX Live mailing list can give you more reliable information.
