### ISSUE TITLE
dvisvgm crops integral sign when unicode-math is enabled

### ISSUE THREAD

**Issue by bk322** [mgieseki/dvisvgm#48]
When xetex's unicode-math is enabled dvisvgm crops integral sign:

MWE:

```latex
\documentclass[border=1pt]{standalone}
% math packages:
\usepackage{amsmath}

% math font:
\usepackage{unicode-math}

\usepackage[active]{preview}

\begin{document}

\begin{preview}
\begin{gather}
\begin{split}
\int \delta(x)  F(x) {\,\mathrm{d} x} = F(0)
\end{split}\notag
\end{gather}
\end{preview}

\end{document}
```

Compilation:

```
$ xelatex -no-pdf mwe.tex
$ dvisvgm -n test.xdv
```

results in:
![test-with-um svg-97x9-500- gwenview-99](https://cloud.githubusercontent.com/assets/875273/8646268/0ce13ec6-2957-11e5-8e27-24643a4397c7.png)

(note the cropped integral sign)

Where as if I comment unicode-math I get the correct output:
![test-no-um svg-97x22-500- gwenview-99](https://cloud.githubusercontent.com/assets/875273/8646271/113de28a-2957-11e5-9d17-47d2cb7bffb4.png)

**Comment by mgieseki** [comment]
I currently can't reproduce the issue. On my system, the integral sign is completely inside the bounding box of the SVG. Do you get the correct bounding box if you call dvisvgm with option `--exact`?

**Comment by bk322** [comment]
When I call it with --exact the issue is gone! Hooray!

On Mon, Jul 13, 2015 at 12:19 PM, Martin Gieseking <notifications@github.com

**Comment by mgieseki** [comment]
Great to hear that the additional option fixes the problem for you. :) One of your font files probably contains misleading glyph metrics so that dvisvgm can't derive correct bounding boxes from them. Option `--exact` always computes the actual glyph extents and doesn't rely of the metrics given in the font file.
