### ISSUE TITLE
Wrong unicode character in latex equation

### ISSUE THREAD

**Issue by jaap-karssenberg** [mgieseki/dvisvgm#52]
Short description
----------------------
Compiling a latex equation into svg with dvisvgm results in the wrong unicode character for the latex "\times" code. Showing some chines character instead of multiplication symbol.

Reporting bug found with dvisvgm version 1.8 - I'm volunteering to test with newer releases if there is an ubuntu / debian package I can install.

Long description
---------------------
As a test case we use dvisvgm to convert the following latex to an svg image:

    \documentclass[12pt]{article}
    \pagestyle{empty}
    \begin{document}
    $$T = 100 \times \frac{L + G}{SR + G}$$
    \end{document}

What I get with dvipng is this:
![equation1](https://cloud.githubusercontent.com/assets/1248286/12198944/8e22d518-b614-11e5-8673-38b3f05d4c36.png)

This is a screenshot of how the svg looks in inkscape:
![screenshot from 2016-01-08 14 35 42](https://cloud.githubusercontent.com/assets/1248286/12199016/26c524ce-b615-11e5-978b-9a9007569c04.png)

As you can see the multiplication symbol is wrong in the svg version. The same rendering is shown by other applications as well, including gnome image viewer and firefox.

When inspecting the source of the svg I see this part:

    <glyph d='M389 278L189 477C177 489 175 491 167 491C157 491 147 482 147 471C147 464 149 462 160 451L360 250L160 49C149 38 147 36 147 29C147 18 157 9 167 9C175 9 177 11 189 23L388 222L595 15C597 14 604 9 610 9C622 9 630 18 630 29C630 31 630 35 627 40C626 42 467 199 417 250L600 433C605 439 620 452 625 458C626 460 630 464 630 471C630 482 622 491 610 491C602 491 598 487 587 476L389 278Z' glyph-name='multiply' horiz-adv-x='777' unicode='㐂' vert-adv-y='777'/>

(scroll towards end of line to see unicode property)

The unicode symbol shows is this one: http://unicode.org/cgi-bin/GetUnihanData.pl?codepoint=3402

Looking at possible unicode signs for multiplication I don't understand how this mix up can happen. See e.g. https://en.wikipedia.org/wiki/Multiplication_sign#Unicode

Attached a zipfile with both dvipng and dvisvgm generated images:
[test_dvisvgm.zip](https://github.com/mgieseki/dvisvgm/files/82730/test_dvisvgm.zip)

Hope this description is helpful for reproducing the issue and pinpointing it.

**Comment by mgieseki** [comment]
The generated SVG file is almost correct. However, most SVG renderers don't support SVG font elements. If you open the file with Opera or Batik Squiggle for example, you should get the correct visual result (also see http://dvisvgm.bplaced.net/Screenshots). Alternatively, you can call dvisvgm with option `-n` to replace the font elements by paths. These SVG files are usually much more portable.

Concerning, the wrong Unicode character assigned: this issue has been fixed in dvisvgm 1.11. The latest version is 1.14.1 and brings some more improvements. Since you're using a pretty old release (1.8.1), you might want to try a more recent one.
Here's your [equation converted with dvisvgm 1.14.1](https://github.com/mgieseki/dvisvgm/files/82762/equation.zip).

**Comment by jaap-karssenberg** [comment]
Hi Martin,

Thanks for the information. Can confirm that indeed using "-n" avoids the issue and that the dvisvgm 1.11 output you share also gives the expected result. 

The "-n" option works well for my use case since I'm only interested in the visual presentation, the text equivalent is handled separately.

Will upgrade as soon as the new version makes it into my package management.

I believe this issue can be closed.

Regards,

Jaap

**Comment by mgieseki** [comment]
Hi Jaap,

great to hear, you could solve the issues with dvisvgm. I'm closing this ticket for now. Feel free to reopen it, if you have further questions on this topic.

Best,
Martin
