### ISSUE TITLE
feature request: encoding in xml tag

### ISSUE THREAD

**Issue by tantau** [mgieseki/dvisvgm#54]
I do not know whether this has already been fixed in the latest release, but I have the following problem: The xml files generated by dvisvgm start with

<?xml version="1.1"?>

However, they should start with

<?xml version="1.1" encoding="utf-8"?>

Background: When an svn-page is embedded in an html, at least on Safari, higher plane Unicode characters are not rendered properly in the current version, but with the encoding explicitly mentioned as above, it works.

**Comment by mgieseki** [comment]
Hm, this seems to be an issue with Safari. UTF-8 should be the default if the encoding isn't specified in the XML declaration and if there's no leading BOM before `<?xml`. Nonetheless, I can add the encoding part again (I removed it in one of the previous releases).
