### ISSUE TITLE
random inverse paths

### ISSUE THREAD

**Issue by michamedia** [mgieseki/dvisvgm#57]
When I convert files randomly this strange behaviour occurs sometimes. The paths of numbers and signs aren´t filled correctly. Any solution or ideas?

`dvisvgm --no-fonts file`

.dvi output
![dvi-output](https://cloud.githubusercontent.com/assets/6643989/14988714/63bd156c-1155-11e6-9514-d33bb09f8a3a.PNG)

.svg output
![svg-output01](https://cloud.githubusercontent.com/assets/6643989/14988715/63be1c46-1155-11e6-83ec-2c4def888735.PNG)

.svg output paths
![svg-output02](https://cloud.githubusercontent.com/assets/6643989/14988713/63bbff60-1155-11e6-802b-713d08cfb0a9.PNG)

**Comment by mgieseki** [comment]
Without further information it's hard to tell why this happens. If possible, please provide a minimal TeX file together with the corresponding DVI that allows to reproduce the issue. It would also be helpful to know the dvisvgm version you're using.

**Comment by michamedia** [comment]
version 1.15.1 64bit on WIndows 7

.tex .dvi and .svg file in a .zip archive:
[latex_test_min.zip](https://github.com/mgieseki/dvisvgm/files/247267/latex_test_min.zip)

**Comment by mgieseki** [comment]
Thanks for the additional information. Unfortunately, I can't reproduce the issue. Your SVG file renders correctly for me (Firefox, Chrome, Inkscape, Squiggle). I also can't find any issues in the generated data. What application do you use to open the SVG file?

**Comment by michamedia** [comment]
Thanks for your fast reply.
And you are right, there is no problem with the file in browsers. I should have tested this first.
I use the svg in Adobe Illustrator and there appears that behaviour. Also in Inkscape there is no such problem. Then I have to check whats the problem with Illustrator. Thanks for this nice utility!
