### ISSUE TITLE
DVI error: DVI format 7 not supported

### ISSUE THREAD

**Issue by grumpyfogey** [mgieseki/dvisvgm#59]
Dear all,

I got the error message above.
I think, it has to do with a very fresh Latex (XeLatex) installation (Tex Live 2016).
I use XeLatex only because it's used by Madoko.
Maybe some of you have a solution or workaround.

Thank you for your help

**Comment by mgieseki** [comment]
XeTeX 0.99995 introduced a new XDV command and therefore bumped the DVI version to 7. As you guessed correctly, dvisvgm 1.15.1 which comes with TeX Live 2016 does not support it, and, unfortunately, there's no easy way to work around it.
However, the required changes to the dvisvgm code are already present in the Git repository (see commit https://github.com/mgieseki/dvisvgm/commit/f7e81d3efbb8cd6a0ebac1e7849f661b32989d74) and will be part of the next dvisvgm release. In the meantime, you probably have to use an older version of Xe(La)TeX or build a more recent version of dvisvgm from source.

**Comment by grumpyfogey** [comment]
Thank you for your fast reply.

Compiling from source is a bit beyond my scope. Last night I found that pLatex does the job.

**Comment by mgieseki** [comment]
Great to hear you found a way around the problem.

**Comment by nrolland** [comment]
I have the exact same problem. 
Trying to compile it from source yields the error 
`configure: error: please install the kpathsea development package`

yet running 
`sudo tlmgr install kpathsea`

yields 
`tlmgr install: package already present: kpathsea`

not sure how to get hold of a binary.
ps : Nix would be great to solve those packages issues.

**Comment by nrolland** [comment]
I don't understand the point in making a distribution like TexLive 2016 if the tools included are not supposed to work together.

**Comment by nrolland** [comment]
After redirecting xelatex 2016 to be xelatex 2015 (and pray) it worked, but the result of the conversion by dvisvgm was bogus, many elements were missing in figures. 

Removing dvisvgm made Madoko convert to png, which has a correct rendering

**Comment by mgieseki** [comment]
Sorry, I'm not a TeX Live maintainer, and therefore can't help with this issue. As far as I know, TeX Live doesn't provide the development files (headers and static libraries) required to build dvisvgm from source. Maybe someone on the TeX Live mailing lists can give some more helpful information:
https://www.tug.org/texlive/lists.html

**Comment by nrolland** [comment]
It seems like there are seperate issues : the texlive itself shipping incompatible tools, and independently of that, the fact that it's impossible to build a new version, as some dependencies (which happen to be in texlive) are nowhere to be found :)

**Comment by nrolland** [comment]
It looks like another compeling case for Nix-style management, as it solves once and for all these kind of questions

**Comment by mgieseki** [comment]
Well, while TeX Live itself doesn't provide the development files, many Linux distros do. Personally, I don't use the original TL binaries but those from Fedora and Ubuntu which also come with the packages texlive-lib-devel and libkpathsea-dev, respectively.

**Comment by nrolland** [comment]
Do you happen to know how one can compile dvisvgm on macos ?

**Comment by mgieseki** [comment]
I'm sorry, I have no access to a Mac and don't know much about macOS. But maybe Rasmus Larsen (see #65) can give you some more information.

**Comment by nrolland** [comment]
thank you

**Comment by nrolland** [comment]
Is there a linux binary distribution somewhere by any chance ?

**Comment by nrolland** [comment]
I am not too familiar with general linux package management : Am I right to say that to build it, one has first to install the dependencies, which are informally listed in the readme ? 
Practically, one has to try to install, look at some error, install missing deps (say autoconf), try again, etc.... ?  

It sounds like a definition of hell, I must have missed something.

**Comment by nrolland** [comment]
I got it to start compiling. this situation looks like the normal state of ubuntu and co regarding dependencies..

**Comment by nrolland** [comment]
almost ! :

> dvisvgm.cpp:72:48: error: ‘CommandLine’ does not name a type
>  static string get_transformation_string (const CommandLine &args) {
