### ISSUE TITLE
OSX compilation - ff-woff

### ISSUE THREAD

**Issue by RasmusWernerLarsen** [mgieseki/dvisvgm#65]
Currently dvisvgm cannot compile on OSX (I've tested on the latest Sierra release) unless you explicitly disable woff.

This is caused, it seems, like a quite trivial include issue in the ff-woff lib. It looks like splinefont is including locale.h and expecting it to contain the locale_t struct. Unfortunately locale_t is not present in locale.h on OSX, it is however present in xlocale.h. I guess this might be caused by locale_t being an old GNU extension, that later became a part of the posix standard.

Regardless, if I replace locale.h with xlocale.h in splinefont.h things build fine. I am, however, a bit unsure how to properly fix this. Adding an ifdef for non-GNU systems might be an approach, but I suspect there's a better solution.

**Comment by mgieseki** [comment]
Thanks for reporting this issue. Unfortunately, I don't have an OS X system available, so I can't actually debug it. Maybe it's sufficient just to check the availability of xlocale.h. [Here is a patch](https://gist.github.com/mgieseki/864030f76f13f397cff1ace6d8de43e5) that includes xlocale.h in splinefont.h if it's present on the build system. Please let me know whether it fixes the build error.

**Comment by RasmusWernerLarsen** [comment]
The patch does it, I can build this on OSX Sierra with default configure options.

The reason I'm looking into this, is actually to get dvisvgm 2.1 into the MacPorts package manager, to make it easily installable to my colleagues (and anyone else who might need it).

Don't know if you have an opinion, but I can just add the patch to the package for now and then update it again whenever you do a new release, or I can wait for you to include it. Whatever fits your schedule best.

Thank you for the extremely quick fix.

**Comment by mgieseki** [comment]
Great, thanks for the confirmation. I also communicated about this issue with Richard Koch yesterday who builds the Mac binaries for TeX Live. The patch seems to fix the build errors there too. I'm currently polishing a couple of further things and will publish version 2.1.1 in the next couple of days.

**Comment by nrolland** [comment]
@RasmusWernerLarsen how did you install texlive-lib-devel and libkpathsea-dev on mac ?

**Comment by RasmusWernerLarsen** [comment]
https://www.macports.org/

sudo port install texlive-bin

It's also a dependency of the "dvisvgm" package, which currently installs 1.5.3, but should soon install 2.1.1.
