### ISSUE TITLE
Eternal loop in case of subprocess failure

### ISSUE THREAD

**Issue by RasmusWernerLarsen** [mgieseki/dvisvgm#68]
We're running dvisvgm as part of an image conversion process, that is running quite a few conversions and we've, until now, had a single case where dvisvgm has entered an eternal loop.

The environment is dvisvgm 2.1.3 on Ubuntu 16.04 x86_64.

We didn't kill the process right away, so I had time to gleam what I could from it. So first I straced it, which showed that it seems to be in a tight loop issuing a wait on process 6420, which unfortunately has died, which causes the wait call to return right away. After that it tries to read up to 512 bytes from file descriptor 7 and starts over.

> wait4(6420, 0x7fff6e9647b0, WNOHANG, NULL) = -1 ECHILD (No child processes)
> read(7, "", 511)                        = 0
> wait4(6420, 0x7fff6e9647b0, WNOHANG, NULL) = -1 ECHILD (No child processes)
> read(7, "", 511)                        = 0
> wait4(6420, 0x7fff6e9647b0, WNOHANG, NULL) = -1 ECHILD (No child processes)
> read(7, "", 511)                        = 0
> wait4(6420, 0x7fff6e9647b0, WNOHANG, NULL) = -1 ECHILD (No child processes)
> read(7, "", 511)                        = 0
> wait4(6420, 0x7fff6e9647b0, WNOHANG, NULL) = -1 ECHILD (No child processes)
> read(7, "", 511)                        = 0
> wait4(6420, 0x7fff6e9647b0, WNOHANG, NULL) = -1 ECHILD (No child processes)
> read(7, "", 511)                        = 0

Now, looking at the filedescriptor map of the process, we learn that 7 is a pipe. (it has some extra file descriptors that are inherited from the php process we use to invoke dvisvgm)

> lr-x------ 1 www-data www-data 64 Apr 27 19:48 0 -> pipe:[1441093]
> l-wx------ 1 www-data www-data 64 Apr 27 19:48 1 -> pipe:[1441094]
> lrwx------ 1 www-data www-data 64 Apr 27 19:48 10 -> socket:[1445079]
> lrwx------ 1 www-data www-data 64 Apr 27 19:48 11 -> socket:[565314]
> lrwx------ 1 www-data www-data 64 Apr 27 19:48 12 -> socket:[1445081]
> lrwx------ 1 www-data www-data 64 Apr 27 19:48 13 -> socket:[565320]
> lrwx------ 1 www-data www-data 64 Apr 27 19:48 14 -> socket:[1445083]
> lrwx------ 1 www-data www-data 64 Apr 27 19:48 15 -> socket:[1441061]
> lrwx------ 1 www-data www-data 64 Apr 27 19:48 16 -> socket:[1441063]
> lrwx------ 1 www-data www-data 64 Apr 27 19:48 17 -> socket:[626229]
> l-wx------ 1 www-data www-data 64 Apr 27 19:48 18 -> /mnt/web-data/sites/plusfrabasistild.systime.dk/web/typo3temp/var/logs/typo3_2102b895fb.log
> l-wx------ 1 www-data www-data 64 Apr 27 19:48 19 -> /mnt/web-data/sites/plusfrabasistild.systime.dk/web/typo3temp/logs/solrfal.log
> l-wx------ 1 www-data www-data 64 Apr 27 19:48 2 -> pipe:[1441095]
> lr-x------ 1 www-data www-data 64 Apr 27 19:48 3 -> /mnt/web-data/sites/plusfrabasistild.systime.dk/web/typo3temp/gt3math/9b526736f221756255d6658305aebb14ce60a6e4.svg.dvi
> lr-x------ 1 www-data www-data 64 Apr 27 19:48 4 -> /dev/urandom
> l-wx------ 1 www-data www-data 64 Apr 27 19:48 5 -> /var/log/newrelic/php_agent.log
> lrwx------ 1 www-data www-data 64 Apr 27 19:48 6 -> socket:[1444907]
> lr-x------ 1 www-data www-data 64 Apr 27 19:48 7 -> pipe:[1441109]
> lrwx------ 1 www-data www-data 64 Apr 27 19:48 8 -> socket:[565305]
> l-wx------ 1 www-data www-data 64 Apr 27 19:48 9 -> /mnt/web-data/sites/plusfrabasistild.systime.dk/web/typo3temp/var/logs/solr.log

Now, putting all this together the only code that matches in dvisvgm is src/Process.cpp, specifically the loop here:

    for (;;) {
        if (out) {
            char buf[512];
            ssize_t len;
            while ((len = read(pipefd[0], buf, sizeof(buf)-1)) > 0) {
                buf[len] = 0;
                *out += string(buf);
            }
        }
        int status;
        waitpid(pid, &status, WNOHANG);
        if (WIFEXITED(status)) { // child process exited normally
            ok = (WEXITSTATUS(status) == 0);
            break;
        }
        try {
            SignalHandler::instance().check();
        }
        catch (SignalException &e) { // caught ctrl-c
            close(pipefd[0]);
            kill(pid, SIGKILL);
            throw;
        }
    }

From just looking at the code, I don't see any breakout code, in case the subprocess returns a non 0 code, which I suspect is what happened here. I'll try and see if I can debug why the subprocess crashed, but for this issue, I just want to report that this loop may need some additional error handling.

**Comment by RasmusWernerLarsen** [comment]
I cannot reproduce the underlying issue. Re-trying the dvisvgm invocation with the same input and same parameters works as expected.

**Comment by mgieseki** [comment]
Hi Rasmus,
thanks for reporting the problem. The function should indeed check the return value of `waitpid` and quit the loop if an error occurred in the child process. I'll have a closer look in the next few days.
