### ISSUE TITLE
Displaced TeX and postscript parts in combination with scalebox

### ISSUE THREAD

**Issue by ernstmoritzhahn** [mgieseki/dvisvgm#70]
I am using fig2dev to transform fig files to graphics consisting of both a TeX and a postscript part (using the output options pstex and pstex_t) which should be placed on top of each other. Then, I include the pstex_t file and rescale it using scalebox, as in the following example:
```
\documentclass{beamer}
\begin{document}
\begin{frame}
    \scalebox{0.4}{\input{dice.pstex_t}}
\end{frame}
\end{document}
```
When applying dvisvgm on the dvi generated by running latex on this file, the positions of the two parts are not synchronised correctly. The problem seems not to be present without the scalebox. (the fact that the pstex part itself is not converted completely correctly is probably due to some features of postscript not being supported by dvisvgm, not related to this bug.)

For a complete example, see the files contained in [shiftbug.tar.gz](https://github.com/mgieseki/dvisvgm/files/1028657/shiftbug.tar.gz).

**Comment by mgieseki** [comment]
Thanks for reporting the bug. I've fixed the positioning issue and will commit the changes after further testing.
The arrow lines seem to be omitted due to a clipping issue. I have to investigate this in more detail. This can take some time, though.

**Comment by ernstmoritzhahn** [comment]
Great, thanks!
