### ISSUE TITLE
Differences in 'stats' command lead to problems building doc in BSD variants

### ISSUE THREAD

**Issue by ernstmoritzhahn** [mgieseki/dvisvgm#72]
The 'stat' command in macOS does not accept the command line parameter '-c' - the according parameter is called '-f' there:
https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/stat.1.html
The same seems to be the case for other BSD variants:
https://www.freebsd.org/cgi/man.cgi?query=stat&sektion=1
This difference leads to problems when building the documentation of dvisvgm due to doc/Makefile.a, line 45:

 		`sed -i "s#\(</refmeta>\)#<refmiscinfo class='date'>$(shell stat -c %y $<)</refmiscinfo>\n\1#" $@; \`

resulting in
```
Making all in doc
stat: illegal option -- c
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
if [ `type -p asciidoc` ]; then \
		asciidoc -a icons -a 'iconsdir=.' -a badges -a 'revnumber=2.1.3' --unsafe -bdocbook -dmanpage -o dvisvgm-man.xml dvisvgm.txt; \
		sed -i "s#\(</refmeta>\)#<refmiscinfo class='date'></refmiscinfo>\n\1#" dvisvgm-man.xml; \
	fi
if [ `type -p xmlto` ]; then \
		xmlto -m ../doc/conf-dblatex-man.xsl --stringparam man.endnotes.list.enabled=0 --stringparam man.endnotes.are.numbered=0 --stringparam man.authors.section.enabled=0 man dvisvgm-man.xml; \
	fi
Input file /Users/emhahn/dvisvgm/doc/dvisvgm-man.xml not found
make[2]: *** [dvisvgm.1] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

```

**Comment by mgieseki** [comment]
Yes, that's a known issue: https://github.com/macports/macports-ports/commit/aa6a8cc84cc076996e0f287395905328ba835337
