### ISSUE TITLE
Feature Request: Add Support For XeLaTeX .XDV Style Links

### ISSUE THREAD

**Issue by cooperstevenson** [mgieseki/dvisvgm#74]
DVISVGM parses hypertext style specials to create SVG links.

XeLaTeX, of course, through the .xdv DVI format, uses a different string pattern to designate links:

> /A<</S/URI/URI(http://portfolio.cooper.stevenson.name)>>

Unfortunately, the TeX-Live (via hyperref package option) does not permit the ability to use 'hypertext' style URL's.

All in all, there is no way to create a document using \fontspec typefaces (not supported by pdflatex) and also have linked DVISVGM documents (really cool feature).

Would you please add support for .xdv hyperlinks?

**Comment by mgieseki** [comment]
I'll add the feature to my to-do list. It requires some refactorings and evaluation of pdf operators since hyperref creates pdf specials for XeTeX. A complete special pair for external links looks like this:
```
pdf:bann<</Type/Annot/Subtype/Link/Border[0 0 1]/C[0 1 1]/A<</S/URI/URI(https://...)>>>>
pdf:eann
```
Anchors and links inside the document (aka "outlines") need further special treatment.

**Comment by cooperstevenson** [comment]
Hi libBlethly,

You're right--there's an option to force the hypperref package to use hypertex style links.

Unfortunately, with the current release of Tex-Live, using the option (\usepackage[hypertex]{hyperref}) yields the following error:

> ! Package hyperref Error: Wrong DVI mode driver option `hypertex',
(hyperref)                because XeTeX is running.

Googling around for the error brings up some interesting results revolving around modifying the \hypersetup directive but nothing turned out fruitful, at least for me.

Your post linked above, actually, was the post that got me thinking about hypertext style links and led to tracking the trouble down.

**Comment by mgieseki** [comment]
I've implemented the evaluation of PDF hyperlink specials as created by the hyperref package when using XeTeX. The handler should correctly recognize internal and external links but I haven't had the time to test it thoroughly. Let me know, if you find any issues.
