### ISSUE TITLE
"PostScript error: undefined in H.S" occurs when a dvi file contains a hyperlink

### ISSUE THREAD

**Issue by libBletchley** [mgieseki/dvisvgm#75]
A `latex`-produced `.dvi` file that includes a hyperlink breaks `dvisvgm`.  This is a sample of the `latex` code:
```
\documentclass[12pt]{minimal}
\usepackage[margin=0mm,nofoot,a5paper]{geometry}
\usepackage[active,tightpage]{preview}
\usepackage{hyperref}

\begin{document}
\begin{preview}

\href{https://github.com/mgieseki/dvisvgm/issues/75}{arbitrarylink}

\end{preview}
\end{document}
```
The use of `\href` is apparently the significant factor.  But theoretically there should be no issue, because the SVG format in fact supports clickable hyperlinks.  This is the `dvisvgm` output:
```
pre-processing DVI file (format 2)
processing page 1
  PostScript error: undefined in H.S
```
Versions:
```
$ latex -v
pdfTeX 3.14159265-2.6-1.40.15 (TeX Live 2015/dev/Debian)
kpathsea version 6.2.1dev
Copyright 2014 Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
Compiled with libpng 1.6.13; using libpng 1.6.13
Compiled with zlib 1.2.8; using zlib 1.2.8
Compiled with poppler version 0.26.5
```
```
$ dvisvgm -V
dvisvgm (TeX Live) 1.8.1
```
(edit)
I'm not sure if I've just duplicated this bug report: https://github.com/mgieseki/dvisvgm/issues/74.  Apologies if I did.  Seems quite similar, although I don't understand why that's characterized as a feature request.  Since both formats (DVI and SVG) include language to specify a hyperlink, then surely it's a bug to fail with an error about something being "undefined" when a hyperlink is encountered.  

**Workaround lacking**
Also note that the other way to produce an SVG file from a LaTeX document is to write a PDF and use `pdftocairo`.  But `pdftocairo` simply neglects to make the URL sensitive (clickable).  That has been reported here: https://github.com/lambdafu/poppler/issues/1.  There is no workaround AFAIK.

**Comment by mgieseki** [comment]
Depending on the selected driver, hyperref creates different special commands representing links. Currently, dvisvgm only supports HyperTeX specials created if the hyperref package is loaded with option `hypertex`:

    \usepackage[hypertex]{hyperref}

 By default, hyperref creates PS specials which are supposed to be used together with dvips.
The reported undefined operator `H.S.` (as well as `H.R`) is called in the PS code but not defined there so that dvisvgm can't evaluate them properly. Thus, I don't consider this a bug in dvisvgm. The PS file created by dvips can't be rendered correctly either without further postprocessing.
Issue #74 is not related to this one.

**Comment by libBletchley** [comment]
I'm so happy to hear about the `hypertex` option.  It resolved my immediate problem.

(BTW, I also tried converting the PDF variation to SVG using Inkscape, which also neglected to make the link clickable, and ImageMagick simply produced garbage).

**Comment by mgieseki** [comment]
I'm glad to hear that you could solve the problem with the additional package option.

**Comment by libBletchley** [comment]
Just a heads up, when the graphviz tool "`dot`" has a node for which the image is a `dvisvgm`-produced SVG file with hyperlinks, the node on the resulting SVG diagram ends up empty.  But firefox renders the `dvisvgm`-produced SVG file just fine, so this is likely a graphviz problem.
