### ISSUE TITLE
Incorrect line-width with asymptote .eps

### ISSUE THREAD

**Issue by Doeme** [mgieseki/dvisvgm#77]
Hi

When converting from an .eps generated from asymptote to .svg, the line-widths don't change when they should.
I [attached](https://github.com/mgieseki/dvisvgm/files/1425226/u.zip) an example .eps-file with the converted .svg as well as the source .asy

Note that the actual linewidths seem to come from the 
```
[ 0.75 0 0 0.75 0 0] concat
```
line, and dvisvgm seems to rely solely on
```
0.5 Setlinewidth
```
even though in a strange way ( Setting it to 1.5 changes nothing, 10.0 results in stroke-width=2, 20.0 in stroke-width=5)

Also note that ghostscript by itself has no problem rendering the proper line-widths, i.e.
```
gs -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r500 -dGraphicsAlphaBits=4 -sOutputFile=test.png test.eps
```
Yields a correctly rendered png

Edit: I'm using ghostscript-9.21, dvisvgm-2.2, and asymptote-2.41-r1 all running on Gentoo Linux.

**Comment by mgieseki** [comment]
Thanks for reporting this issue. It's a stupid bug that was easy to fix. I'll commit the patch after few more testing.
