### ISSUE TITLE
PostScript error: undefined in TeXDict

### ISSUE THREAD

**Issue by anthonynorthrup314** [mgieseki/dvisvgm#78]
I know there is an existing/previous issue #62 so I've followed the steps you listed for troubleshooting, and nothing seems to be wrong.

```
$ dvisvgm test.dvi -n
WARNING: font file 'cmr10.pfb' not found
pre-processing DVI file (format version 2)
WARNING: PostScript header file tex.pro not found
WARNING: PostScript header file texps.pro not found
WARNING: PostScript header file special.pro not found
PostScript error: undefined in TeXDict
$ kpsewhich tex.pro
/usr/share/texmf-dist/dvips/base/tex.pro
$ dvisvgm -V1 | grep kpathsea
kpathsea:    6.2.3
$ kpsewhich --version | grep kpathsea
kpathsea version 6.2.3
$ ldd `which dvisvgm` | grep kpathsea
	libkpathsea.so.6 => /usr/lib/libkpathsea.so.6 (0x00007f9d2be6e000)
$ ldd `which kpsewhich` | grep kpathsea
	libkpathsea.so.6 => /usr/lib/libkpathsea.so.6 (0x00007f473705d000)
```

I checked the config to see if it's not finding kpathsea functions, and this was the result:
```
$ ./configure | grep kp
checking kpathsea/kpathsea.h usability... yes
checking kpathsea/kpathsea.h presence... yes
checking for kpathsea/kpathsea.h... yes
checking for kpse_find_file in -lkpathsea... yes
checking kpathsea version... "6.2.3"
checking if the kpathsea headers are C++ safe... yes
```

I'm using the latest version from source 2.2.1.
For some reason it's showing up as being 2.1.3
```
$ dvisvgm --version
dvisvgm 2.1.3
```

**Comment by anthonynorthrup314** [comment]
The file I'm using to test is attached below, as well as the steps used to create the DVI file.

Steps:
```
$ latex test.tex -interaction=batchmode -halt-on-error
<long and unimportant, it succeeds>
$ dvisvgm test.tex -n
<errors>
```

test.tex:
```
\documentclass[preview]{standalone}

\usepackage[english]{babel}
% \usepackage[utf8x]{inputenc}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{dsfont}
\usepackage{setspace}
\usepackage{tipa}
\usepackage{relsize}
\usepackage{textcomp}
\usepackage{mathrsfs}
\usepackage{calligra}
\usepackage{wasysym}
\usepackage{ragged2e}
\usepackage{physics}
\usepackage{xcolor}
\usepackage[UTF8]{ctex}
\linespread{1}

\begin{document}

\centering Stuff

\end{document}
```

**Comment by mgieseki** [comment]
> $ dvisvgm --version
dvisvgm 2.1.3

If that's the output, you most likely don't run the binary built from the 2.2.1 sources. Please check whether there's another dvisvgm present and if you call the correct one (e.g. `/usr/bin/dvisvgm` vs. `/usr/local/bin/dvisvgm`).
What Linux distro do you use? Did you install the development files of libkpathsea that come with your distro?

**Comment by anthonynorthrup314** [comment]
I'm using Arch Linux, just installed yesterday. I didn't install the development files, but I assumed the configuration program was checking for that when it looked for the header files.

Here's the one I'm using:
```
$ which dvisvgm
/usr/local/bin/dvisvgm
```

When I run `sudo make uninstall` it goes back to /usr/bin, so I'm pretty sure it's the one I built.

**Comment by anthonynorthrup314** [comment]
Note: If I try using the one in my bin directory it has a segfault, which is why I'm trying to build from source.
```
$ dvisvgm test.dvi -n
pre-processing DVI file (format version 2)
processing page 1
  computing extents based on data set by preview package (version 11.91)
  width=22.7768pt, height=7.319pt, depth=7.31985e-06pt
  graphic size: 22.7768pt x 7.31901pt (8.00514mm x 2.57234mm)
Segmentation fault (core dumped)
```

Here's the gdb from that
```
(gdb) run test.dvi -n
Starting program: /usr/bin/dvisvgm test.dvi -n
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
pre-processing DVI file (format version 2)
processing page 1
  computing extents based on data set by preview package (version 11.91)
  width=22.7768pt, height=7.319pt, depth=7.31985e-06pt
  graphic size: 22.7768pt x 7.31901pt (8.00514mm x 2.57234mm)

Program received signal SIGSEGV, Segmentation fault.
0x00005555556394f0 in Subfont::decode(unsigned char) ()
```

**Comment by mgieseki** [comment]
Thanks for the additional info. There are obviously two different issues. I can reproduce the segfault. The bug is still present in dvisvgm 2.2.1. I'll commit the fix soon.

Concerning the kpathsea problem, I can't really help here. If you build dvisvgm from the 2.2.1 sources, you should definitely get a binary that reports the correct version. I don't know what happened here. Maybe the TeX Live maintainer of Arch Linux get give you more helpful information.

**Comment by anthonynorthrup314** [comment]
I'm glad something was worth mentioning. I'll look into the building issue myself, you can close if that's the only reason this issue is still open.

**Comment by mgieseki** [comment]
OK, thanks for reporting the memory issue. Hope you get the build problem sorted too. Feel free to reopen the ticket again or create a new one if you stumble over further problems with dvisvgm.

**Comment by anthonynorthrup314** [comment]
I've redownloaded the 2.2.1 release source and compiled again, it now properly reports version 2.2.1. I'm not sure what was wrong, but it appears to be fixed now. I look forward to 2.2.2 for fix of the memory issue.

**Comment by anthonynorthrup314** [comment]
I'm not sure how to reopen, but now that I have the version I'm building working, it's still having the same file not found errors. Below are the same steps as before.

```
$ dvisvgm --version
dvisvgm 2.2.1
$ dvisvgm test.dvi -n
WARNING: font file 'cmr10.pfb' not found
pre-processing DVI file (format version 2)
WARNING: PostScript header file tex.pro not found
WARNING: PostScript header file texps.pro not found
WARNING: PostScript header file special.pro not found
PostScript error: undefined in TeXDict
$ kpsewhich tex.pro
/usr/share/texmf-dist/dvips/base/tex.pro
$ dvisvgm -V1 | grep kpathsea
kpathsea:    6.2.3
$ kpsewhich --version | grep kpathsea
kpathsea version 6.2.3
$ ldd `which dvisvgm` | grep kpathsea
	libkpathsea.so.6 => /usr/lib/libkpathsea.so.6 (0x00007fe2605ec000)
$ ldd `which kpsewhich` | grep kpathsea
	libkpathsea.so.6 => /usr/lib/libkpathsea.so.6 (0x00007f0b78fc0000)
```
