### ISSUE TITLE
PostScript header file not found

### ISSUE THREAD

**Issue by anthonynorthrup314** [mgieseki/dvisvgm#80]
I'm not sure how to reopen, but now that I have the version I'm building working, it's still having the same file not found errors. Below are the same steps as before.

```
$ dvisvgm --version
dvisvgm 2.2.1
$ dvisvgm test.dvi -n
WARNING: font file 'cmr10.pfb' not found
pre-processing DVI file (format version 2)
WARNING: PostScript header file tex.pro not found
WARNING: PostScript header file texps.pro not found
WARNING: PostScript header file special.pro not found
PostScript error: undefined in TeXDict
$ kpsewhich tex.pro
/usr/share/texmf-dist/dvips/base/tex.pro
$ dvisvgm -V1 | grep kpathsea
kpathsea:    6.2.3
$ kpsewhich --version | grep kpathsea
kpathsea version 6.2.3
$ ldd `which dvisvgm` | grep kpathsea
	libkpathsea.so.6 => /usr/lib/libkpathsea.so.6 (0x00007fe2605ec000)
$ ldd `which kpsewhich` | grep kpathsea
	libkpathsea.so.6 => /usr/lib/libkpathsea.so.6 (0x00007f0b78fc0000)
```

**Comment by mgieseki** [comment]
Sorry, I can't really help you with this issue. It doesn't seem to be related to dvisvgm. If the correct library is linked, it probably doesn't use the same texmf configuration as it does in case of kpsewhich or the dvisvgm binary that comes with Arch Linux. This seems to be an issue with your TeX Live environment. Maybe you can ask someone on the TeX Live mailing list or the Arch Linux maintainer of the TeX Live packages.

**Comment by anthonynorthrup314** [comment]
Sounds good, for now I'm just going to rig it to use kpsewhich via a Process object. I'll contact some others for further assistance. Thanks again.

**Comment by ghostnation66** [comment]
Hey @anthonynorthrup314 did you ever figure out a solution to this? I'm still going through some issues on my archlinux system trying to use dvisvgm on a .dvi file. Thanks in advance for your help!

**Comment by anthonynorthrup314** [comment]
@ghostnation66 it's actually been long enough I don't have those files around anymore. And I have no idea what I meant by "rig it to use kpsewhich via a Process object". I can try to dig a little more, but right now I'm not sure I'll be of help. Sorry

**Comment by ghostnation66** [comment]
> [@ghostnation66](https://github.com/ghostnation66) it's actually been long enough I don't have those files around anymore. And I have no idea what I meant by "rig it to use kpsewhich via a Process object". I can try to dig a little more, but right now I'm not sure I'll be of help. Sorry
> 
> Best advice I got from ChatGPT trying to figure out what I meant:
> 
> var kpseProcess = new Process();
> kpseProcess.StartInfo.FileName = "kpsewhich";
> kpseProcess.StartInfo.Arguments = "libname.so";
> kpseProcess.StartInfo.RedirectStandardOutput = true;
> kpseProcess.StartInfo.UseShellExecute = false;
> 
> kpseProcess.Start();
> string libPath = kpseProcess.StandardOutput.ReadToEnd().Trim();
> kpseProcess.WaitForExit();
> 
> Console.WriteLine($"Library found at: {libPath}");
> 
> using System;
> using System.Diagnostics;
> 
> class Program
> {
>     static void Main()
>     {
>         var process = new Process();
>         process.StartInfo.FileName = "dvisvgm";
> 
>         // Pass your dvi file and output settings
>         process.StartInfo.Arguments = "--no-fonts input.dvi -o output.svg";
> 
>         process.StartInfo.EnvironmentVariables["LD_PRELOAD"] = "/custom/path/to/libcustom.so"; // libPath from above snippet
> 
>         // Ensure environment variables are respected
>         process.StartInfo.UseShellExecute = false;
>         process.StartInfo.RedirectStandardOutput = true;
>         process.StartInfo.RedirectStandardError = true;
> 
>         process.Start();
> 
>         string output = process.StandardOutput.ReadToEnd();
>         string errors = process.StandardError.ReadToEnd();
>         process.WaitForExit();
> 
>         Console.WriteLine($"Output: {output}");
>         Console.WriteLine($"Errors: {errors}");
>     }
> }
> 
> Explanation of `LD_PRELOAD` [https://man7.org/linux/man-pages/man8/ld.so.8.html](https://man7.org/linux/man-pages/man8/ld.so.8.html#:~:text=LD_PRELOAD%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20A%20list%20of%20additional%2C%20user%2Dspecified%2C%20ELF%20shared%20objects%20to%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20be%20loaded%20before%20all%20others.%20%20This%20feature%20can%20be%20used%20to%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20selectively%20override%20functions%20in%20other%20shared%20objects.)

Thanks a ton, I'll look into this and report back. I appreciate your time! Do you think it's an issue with the way the dvisvgm binary is packaged for arch (Im using arch). If I get it from ubuntu's repo, would it work?

**Comment by ghostnation66** [comment]
Hey @anthonynorthrup314 I found this repo: https://github.com/WojciechMula/pydvi2svg

It does exactly what I needed: convert .dvi files to svg. I have just tested it briefly but it works. Let me know if you are interested in setting up and I can help you do it. I've forked it and contacted the original repo maintainer because I was kind of stunned by how well and seamless it appears, and by the fact that it's all basically python (python 2.54 no less). I'd be interested in working on it to move it's functionality up into the python3 domain if possible.

**Comment by anthonynorthrup314** [comment]
@ghostnation66 Thanks, but I'm no longer working with this anymore. As I said above it's been quite a bit of time and I don't have those project files handy anymore. If you found something that works, awesome! I'm mostly on this for record-keeping purposes now, and am unlikely to continue or know much about development with it at this point
