### ISSUE TITLE
An issue with slant font

### ISSUE THREAD

**Issue by cwtex4110** [mgieseki/dvisvgm#82]
This may not be an issue, it could be due to that I do not know how to add option to dvisvgm command.

I have developed a Chinese TeX system called cwTeX:
http://homepage.ntu.edu.tw/~ntut019/cwtex/cwtex.html

The system is a preprocessor, built on MiKTeX, plus some Chinese fonts.
It has been used to typeset many textbooks and papers in Taiwan.

I also adapt tex4ht to handle Chinese, in which dvisvgm is used.
When the tex4ht is used to convert some Chinese "slant" font, 
it produces incorrect result.

Instead of showing a mwe, let me show the result from mwe.
First, svg-bug.pdf is the result from pdflatex (not tex4ht), the first line uses 
ordinary font, the second line uses the same font, but slanted by .167.
For example, cwTeXms0 is from cwTexm0.pfb, but slanted 0.167.
Part of the map file is shown below:

cwTeXms0  cwTeXm0 ".167 SlantFont" <cwTeXm0.pfb
cwTeXms1  cwTeXm1 ".167 SlantFont" <cwTeXm1.pfb

[svg-bug.pdf](https://github.com/mgieseki/dvisvgm/files/1595232/svg-bug.pdf)

Now, when I use tex4ht, the results are (.svg have been converted to .jpg):

![svg-bug0x](https://user-images.githubusercontent.com/34418976/34462471-d5f304d0-ee7f-11e7-8fa9-3b977765396a.jpg)
![svg-bug1x](https://user-images.githubusercontent.com/34418976/34462472-d619b3f0-ee7f-11e7-804b-e18b1c601434.jpg)

The first line is correct (same as .pdf above), the second line (slant font) is incorrect in that 
character space is too large.

I hope my description is clear enough. If further information is needed, please let me know.
Many thanks!

Tsong-Min Wu
Department of Economics
National Taiwan University

**Comment by mgieseki** [comment]
Thanks for reporting this issue. Without an MWE  it's hard it's almost impossible to find the reason for the wrong spacing, though, since there are many parameters involved. I need to reproduce your example and trace the executed code in order to track down the reason. So if possible, please post all files that are not provided by MiKTeX but required to regenerate your example locally. Then I can have a closer look in the next couple of days.

**Comment by mgieseki** [comment]
Thanks again for sending the files (privately).
