### ISSUE TITLE
alignment of "inline" svg

### ISSUE THREAD

**Issue by u-fischer** [mgieseki/dvisvgm#83]
I'm trying to create small svg pictures which aligns correctly inside text. 

My first try was with the preview package:
```
\documentclass{article}
\usepackage[active,tightpage]{preview}
\begin{document}
\begin{preview}$x=y$\end{preview} 
\end{document}
```

I created with this two math svg (the second with x=x) and according to the message the depth was correctly recognized:

```
G:\Z-Test>dvisvgm -o math2.svg −−bbox=preview  test-utf8
pre-processing DVI file (format version 2)
processing page 1
  applying bounding box set by preview package (version 11.91)
  width=25.3138pt, height=4.80742pt, depth=2.44632pt
  graphic size: 25.3138pt x 7.25374pt (8.8968mm x 2.5494mm)
  output written to math2.svg
1 of 1 page converted in 1.01 seconds

G:\Z-Test>dvisvgm -o math1.svg −−bbox=preview  test-utf8
pre-processing DVI file (format version 2)
processing page 1
  applying bounding box set by preview package (version 11.91)
  width=25.7675pt, height=4.80742pt, depth=0.501877pt
  graphic size: 25.7675pt x 5.3093pt (9.05625mm x 1.866mm)
  output written to math1.svg
1 of 1 page converted in 1.002 seconds
```

But the depth is not taken into account when trying to use them in a simple html:

```
<html>
<BODY>
text <img src="math1.svg"/> text <img src="math2.svg"/>
</BODY>
</html>
```
![image](https://user-images.githubusercontent.com/4047173/34831093-39ac43ba-f6e6-11e7-9ee0-395c096c4e28.png)

Should this work or did I misunderstood the documentation?

**Comment by mgieseki** [comment]
The values printed to the console are derived from the data present in the DVI file. Unfortunately, it's not possible to  store baseline information in the SVG file so that it's automatically aligned with the baseline of an HTML document. You have to tweak the vertical alignment of the embedded SVG files manually, e.g. with `<img src="math2.svg" style="vertical-align:-2.437pt"/>`, where the value of the `vertical-align` property is the negative depth value converted to PS points (dvisvgm prints lengths in TeX points).

**Comment by u-fischer** [comment]
So I did misunderstand the docu ;-) and the preview special can be only used as info for later processing. I suspected it already: I played a bit with the viewport in the svg and while I could move the content around it also always got clipped when going below the baseline.  Thanks for the fast answer.

**Comment by mgieseki** [comment]
Yes, sorry. Maybe I should reword the paragraph of the documentation to make it clearer that the preview data can only be used to compute and print the box extents for further post-processing.
