### ISSUE TITLE
Feature Request: Support 'px' Units in SVG Output

### ISSUE THREAD

**Issue by cooperstevenson** [mgieseki/dvisvgm#85]
Hi,

Is it possible to create a switch (--px, perhaps) that specifies that the SVG should be output using 'px' units? Thanks!

**Comment by mgieseki** [comment]
That would be a huge amount of (boring :-)) work because the current code is based on PS/SVG point units.  At the moment, I'd rather not invest my spare time to implement this. I guess, it would be much easier to post-process the SVG files and scale the length values accordingly.

**Comment by cooperstevenson** [comment]
No worries--I confess I was tying to be lazy. Please close if you like.

**Comment by mgieseki** [comment]
Thanks for your understanding. I hope you can modify the SVG output as desired without too much effort.

**Comment by cooperstevenson** [comment]
I believe [I found a tool](https://github.com/Zverik/svg-resize) that will resize the output as described. In my limited tests svg-resize seems to work just fine.
