### ISSUE TITLE
Incorrect depth

### ISSUE THREAD

**Issue by baskerville** [mgieseki/dvisvgm#89]
I've been using *dvisvgm* as part of a *pandoc* filter that replaces occurrences of `$…$` by SVG images. Given a depth *d*, I'm computing the vertical align, in ems, as *-d / f*, where *f* is the default font size. It seems to work fine for most formulas. It however fails for the following TeX file (and a few others):

```latex
\documentclass[preview, border=1pt]{standalone}
\usepackage{amsmath}
\usepackage{amsfonts}
\begin{document}
$x\times y\cdot z$
\end{document}
```

I can produce an SVG file with:
```shell
latex formula.tex
dvisvgm -e -n formula.dvi
```

The output provides the following dimensions:
```
  width=35.091148pt, height=5.938885pt, depth=1.021115pt
  graphic size: 35.091148pt x 6.96pt (12.333128mm x 2.44616mm)
```

In the following graphic, the baseline computed from the above dimensions (at *1.02115/6.96* of the height) is drawn in red and the expected baseline is drawn in blue:

![formula](https://user-images.githubusercontent.com/159419/42727512-b8fb1134-87a8-11e8-89b7-da4abb033509.png)

I'm using *dvisvgm* 2.3.5.

**Comment by mgieseki** [comment]
Thanks for reporting this issue and the detailed description. I could reproduce the problem and already fixed the affected code. I'll commit the changes after a bit more testing.
