### ISSUE TITLE
--disable-bundled-libs acts like --enable-bundled-libs

### ISSUE THREAD

**Issue by hartwork** [mgieseki/dvisvgm#91]
Hi!

Maybe not the most important issue of the worlds but maybe also not to hard to get right:

When reviewing edd9067851f671254c9c03d083efc544b5fdcc9a for #90 last time I missed that with the current implementation has broken `--disable-bundled-libs` because `action-if-given` is `use_bundled_libs=yes`. That part would need to go to `action-if-not-given` instead and `action-if-given` can be empty (if the variable name uis changed to `enable_bundled_libs`) or `use_bundled_libs=$enableval`, I believe but would need testing. https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Package-Options.html knows more.

Best, Sebastian

**Comment by mgieseki** [comment]
Aargh, right. I simply don't manage to memorize the semantics of `AC_ARG_ENABLE`. But it's easy to fix. I'm going to push the patch in a couple of minutes.

**Comment by hartwork** [comment]
Same here with `AC_ARG_ENABLE`.

Could it be that the default has flipped now? autoconf docs say `If no argument is given, it defaults to ‘yes’ but docs here say `@<:@default=no@:>@`. There is no code to enforce either now.

**Comment by mgieseki** [comment]
For me, it now works as expected. When calling `configure` without further options, it's identical to `--disable-bundled-libs`. Seems the documentation is not quite correct.

**Comment by hartwork** [comment]
I get this code in `configure` from `autoconf`:
```
# Check whether --enable-bundled-libs was given.
if test "${enable_bundled_libs+set}" = set; then :
  enableval=$enable_bundled_libs;
fi
```
So the default is unset `${enable_bundled_libs}` which means disabled regarding comparing against `yes`. So I guess you're right about the wrong upstream docs.
