### ISSUE TITLE
feature request: disable building man pages for release

### ISSUE THREAD

**Issue by mojca** [mgieseki/dvisvgm#93]
I would like to request the ability NOT TO build the man page (and possibly other files) when the file(s) already exists(s), which is usually the case in release anyway.

(Please excuse me if I understood this wrong.)

A bit of background:

When building dvisvgm inside MacPorts some users were recently unable to build it due to a bug in `xmlto` (clearly a completely unrelated bug elsewhere), but this was unnoticed on our build server because `xmlto` would only run when it was present (along with all other dependencies for building documentation), so it only affected those users who accidentally had another package installed.

I looked, but I didn't find any easy way to prevent running it, short of providing some hacks (define some cache variables when running `configure`) or patching the `configure` script to remove the parts responsible for building man pages.

We try to avoid "opportunistic use" of dependencies if possible, so I would like to disable running `asciidoc`, `xmlto` etc. "just because they are there". Usually at least they would be run only if the files that are needed do not exist.

@kencu also pointed out that Mac OS X 10.4 (Tiger) completely refuses to build `dvisvgm` when `asciidoc` is missing (which is not the case on newer systems).

@ryandesign @Schamschula

**Comment by mgieseki** [comment]
I can add an configuration option to force the build system not to create the man page. However, it's probably better to fix the Makefile so that `dvisvgm.1` gets only recreated if `dvisvgm.txt.in` is newer.

**Comment by mgieseki** [comment]
I've added option `disable-manpage` to `configure` and also fixed the time stamp issue. If the new option is not given, the man page should now only be generated if `dvisvgm.txt.in` is newer than `dvisvgm.1`.
