### ISSUE TITLE
feature request: decouple --enable-bundled-libs

### ISSUE THREAD

**Issue by mojca** [mgieseki/dvisvgm#94]
While trying to update `dvisvgm` in MacPorts I noticed that some new libraries are needed which have not been packaged yet (for example `xxhash`). All of these libraries (`brotli`, `potrace`, `woff2`, `xxhash`, ...) are bundled in the sources, so they are easy to use, but I did not find an easy way to only use the bundled `xxhash`, while using other libraries from the distribution. There is a `configure` option `--enable-bundled-libs`, but that one is an "all-or-nothing" switch.

See also this thread:
* https://tug.org/pipermail/tlbuild/2018q3/004267.html

@norbusan

**Comment by norbusan** [comment]
Yes, on Debian I have packaged xxhash before updating the binaries. There is no single switch for each of the libs, just a catch all. Thus, you either have to package the missing ones, or completely use the included ones.

**Comment by norbusan** [comment]
See especially https://tug.org/pipermail/tlbuild/2018q3/004280.html

**Comment by norbusan** [comment]
See also https://tug.org/pipermail/tlbuild/2018q3/004291.html for a patch to enable external libs and still make sure that the actually shared libs are included in the load process.

**Comment by mgieseki** [comment]
Thanks for the feedback. The current solution is probably too restrictive. I'll see if I can replace the a-or-nothing approach with something more flexible but without the need. I prefer not to hardcode the library names when linking against the system libs, though.

**Comment by norbusan** [comment]
@mgieseki Indeed, hard coding the lib names is not good, but on Debian I can do this because there is no other provider of libraries, so the names are known.

It is probably a bit a pain, but best would be to have --enable-system-foobar together with --foobar-include and --foobar-ldflags (or similar) for each of the additional libraries.

You can look into the TL automake sources for inspirations.

Thanks a lot

Norbert

**Comment by mgieseki** [comment]
I've changed the behavior of `--disable-bundled-libs` so that the build system now only links the shared libs if they are actually available. Otherwise, it falls back to the bundled version. If possible, please try out the latest version in the master branch and let me know if there are any further issues.

**Comment by mojca** [comment]
Version 2.6.1 works fine for me. The only downside is that I didn't find the feedback about which libraries will be used from the system and which ones will use the bundled version.

**Comment by mgieseki** [comment]
Right, there is no explicit output yet about whether a system or bundled lib is used. Currently, the information can only be deduced from the output of `configure`, e.g.: 
```
checking potracelib.h presence... yes
checking for library containing potrace_trace... -lpotrace
checking for xxhash.h presence... yes
checking for library containing XXH32... -lxxhash
checking for BROTLI... yes
checking for WOFF2... yes
```
System libraries of `potrace`, `xxhash`, `brotli`, and `woff2` found.

----
```
checking potracelib.h presence... no
checking for xxhash.h presence... no
checking for BROTLI... no
checking for WOFF2... no
```
No system libraries found, use corresponding bundled libs instead.

**Comment by mojca** [comment]
See also http://tug.org/svn/texlive?view=revision&revision=49020 for the patches that @kberry added on top of `dvisvgm` to make it suit TL better. Maybe you could talk to him to try to minimize the patching needed for TeX Live inclusion?

**Comment by mgieseki** [comment]
> I didn't notice any specific bugs, I was just wondering if there was a way to minimize the amount of patches needed for http://tug.org/svn/texlive/trunk/Build/source/texk/dvisvgm/TLpatches.

Unfortunately, I'm not an expert for the TeX Live build scripts and currently don't have the time to dig deeper into them. So I guess, I can't really help here at the moment. Nonetheless, if you have suggestions for improvements that work equally well for TeX Live and standalone builds, please let me know.
