### ISSUE TITLE
feature request: responsive SVG: command option for omitting width and height attributes 

### ISSUE THREAD

**Issue by agrahn** [mgieseki/dvisvgm#99]
Could an option be added to `dvisvgm` that would allow an embedded SVG to scale automatically to the size of its container (or browser window, if viewed standalone)? For this, omitting the `width` and `height`attributes from the `<svg>` tag would be sufficient.

Viewing `beamer`-class-based standalone SVGs is a possible application.

**Comment by mgieseki** [comment]
You can already achieve this with option `--zoom`: A negative zoom factor removes the `width` and `height` attributes from the `svg` element.

**Comment by agrahn** [comment]
Apologies for the noise ;).

**Comment by mgieseki** [comment]
Absolutely no problem. Feel free to ask any questions here.
